# -*- coding:utf-8-*-
#+TITLE: 迪拜6天
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 概述
今年公司组织的旅游线路，原本是想去沙巴或柬埔寨，结果人少，不成团，只能另选阿联酋迪拜的线路。这次旅行安排总体来说，不管是深圳这边的旅游公司，还是当地的地接导游，服务都不错，两边导游都很尽职尽责。旅行过程中的团餐也不错，比之前去日本和巴厘岛好多了。

这次去的时候正好赶上伊斯兰教的斋月，有一些当地的忌讳需要遵守，比如不要当着当地人面吃吃喝喝，其他没有太大的影响。

这篇游记主要介绍此次旅游过程中的一些见闻，供大家参考，如果能帮到一二，我会很开心，希望读者都能有个愉快舒心的假期。

* 第一天
行程：香港-->迪拜

14:30从蛇口油轮码头乘船，大约半小时到达香港机场。第一次知道从香港乘坐飞机是可以退税的。详见[[http://www.mafengwo.cn/wenda/detail-8915377.html][香港机场离境退税问题]]

7:00左右乘坐著名的阿联酋航空（EK383 空客A380）飞往迪拜。原本是晚上6:25，由于前序航班EK382晚点半个小时，七点多才起飞。路上耗时9个小时左右，当天晚上当地11点左右到达机场，12点左右入住。航班起落情况可以使用“飞常准”app来查询。

当地时间晚上一点多入住[[http://www.mafengwo.cn/hotel/77809.html?iMddid%3D11214%25EF%25BC%2589%25E3%2580%2582%25E5%258A%259E%25E7%2590%2586%25E5%25AE%258C%25E5%2585%25A5%25E4%25BD%258F%25E6%2589%258B%25E7%25BB%25AD%25EF%25BC%258C%25E6%2594%25B6%25E6%258B%25BE%25E5%25A5%25BD%25E5%2587%2586%25E5%25A4%2587%25E7%259D%25A1%25E8%25A7%2589%25E5%25B7%25AE%25E4%25B8%258D%25E5%25A4%259A%25E5%25B0%25B1%25E6%2599%259A%25E4%25B8%258A%25E4%25B8%25A4%25E7%2582%25B9%25E4%25BA%2586][迪拜节日城皇冠假日酒店]]。 办理完入住手续，收拾好准备睡觉差不多就晚上两点了。

出行前导游介绍，虽然这个是当地的五星级酒店，但是不能和国内的五星级相比，所以对酒店的预期就稍微低点。但是此次出行全程入住该酒店，该酒店的服务不错，设施齐全，完全超出了预期。看了一下单独预订的价格，也不算贵。

酒店楼顶有健身房和游泳池，出行前想着应该没时间游泳，但是还是有点后悔应该带上游泳装备的。上面都没什么人，自己玩应该也挺开心的。

* 第二天 迪拜
行程：朱美拉海滩，朱美拉露天市场，运河，香料街，黄金街

一觉睡到早上8:00，然后去酒店的L层吃自助早餐，餐厅门口会有人登记房号。个人感觉早餐虽然总类不多，但是味道还可以，但是里面的果干，椰枣什么太甜，不合我口味，我吃了一些水果什么的就算了。此外还有炒米饭，面条，煎蛋，各种面包，水果沙拉，三文鱼等，基本上和其他酒店自助早餐差不多。

10:00出发，导游（地接导游，后不再特说明）在乘车过程中，根据路过的住宅区，介绍了迪拜新城区和老城区概况，我们看到路边一幢幢的公寓，导游说着是当地的安置房，谁家生儿子了，政府就分一套，壕的不行。迪拜其实没有之前传的那么夸张，什么遍地都是跑车，根据几天在当地的游览过程看，最多的是日本车，尤其是丰田，非常多，看到所有的出租车都是丰田凯美瑞。

到达帆船酒店旁边的朱美拉海滩。海滩并不大，有一些人在冲浪，晒太阳，我们在呆了大约有40分钟，太热了，就离开了，当然重点是和帆船酒店拍照。

午饭是自助餐，牛肉不错。

吃过午饭，准备香料街和黄金街，需要乘船过迪拜河，这是一条运河，虽然说是河，其实是海水。


香料街，短短的一条街，两边都是各种香料，走过的时候两边的人会和你打招呼，说“你真漂亮” “你真帅” “我喜欢你”等之类的话，语言不通，夸不到点子上，没啥特别的。


接下来是黄金街，有很多黄金饰品，这条街相对而言比较长，可以十分钟走一下，但是也没有太多看头。

世界上最大的戒指，下面是吉尼斯记录的证书。

然后去的是EMIRATES MALL，介绍说里面有个挺大的滑雪场，没有需求，没有太过留意，反正后面还会去dubai mall和机场免税店。

朱美拉露天市场

* 第三天 阿布扎比
主要景点：扎伊德清真寺，民族文化村

路上随处可见的棕榈树和清真寺

导游给我们介绍说这边的绿色植物很珍贵，看一户人家是不是有钱，不是看他家有飞机还是跑车，而是看他家有几棵树，这边绿色植物很珍贵，街上的花草树木都需要地下预先埋设的黑色管道供水养活。

还有由于空间利用率低，被称为世界上最没用的建筑的“”。

扎伊德清真寺真的很漂亮，整体白色，外观看着很宏伟大气，里面的一些建筑细节又很精致。

去民俗村的路上路过首都之门，最倾斜的建筑，像新娘的婚纱，很有特色。参见[[http://www.mafengwo.cn/photo/poi/5485819_22808437.html][首都之门图片]]


民俗村里面主要是介绍60年代以前没有开采出石油之前阿拉伯人的生活情况。

这边有个小沙滩，水非常清澈。

皇宫酒店，这里曾经有可以取黄金的取款机，现在没有了。

皇宫酒店对面就是速度与激情7里面主角开车穿越的大楼，恩，这个没有太大感觉。

然后去“老北京”餐厅吃饭，路上经过文化广场，导游介绍了阿拉伯咖啡，七杯壶等当前的一些风土人情。


* 第四天 迪拜
主要活动：冲沙，自由行

上午导游安排的是早冲沙，13个人两辆丰田陆地巡洋舰。

和我同车的有两个妹子，车速提不起来，而且她们还晕车。冲沙如果车速快的话还是很刺激的。

但是冲沙地点所在的沙漠完全不是我想象的沙漠，营地只有几匹马和瘦了吧唧的几头骆驼。

团里另外几个小伙伴自费购买了晚冲沙，场地明显比我们的要好，盗她们图展示一下：

这才是我想象的沙漠

和沙漠里的夕阳

早冲沙7:00开始，结束回酒店的时候都才10点，下午是自由行，考虑到第二天去dubai
mall时间不够，所以休息一个小时之后，喊着小伙伴去了dubai mall附近逛了一下午。

打车过去，车费大约35迪拉姆，酒店前台可以换货币，比外面要低一点，100美元换350迪拉姆，外面大约360的样子。

IOS也有个APP，可以用来查找店铺，开启蓝牙之后，还可以导航。。。划重点。。可以导航

dubai mall 毗邻哈里发塔（迪拜塔），开始给哈里发塔拍照。

拍完还遇到惠州一帮大爷大妈们，他们拍照更拼。

阳光下去点之后，附近就出现了专职拍照的工作人员，帮着大爷大妈和摄影师翻译了一下价格，一张照片85迪拉姆，其实挺贵的了。大爷大妈想从摄影拷底片，对方不让。

出门没带水，口渴，回商场G层超市买了两桶1.5L的矿泉水，然后等七点半开始的音乐喷泉（每隔半小时一次）。这里要感谢DDM的建议：商场L1层苹果专卖店的阳台是最佳观景地点，视野棒棒的。

第一次喷泉音乐有点短，等第二次的时候发现旁边迪拜塔也有灯光表演。

* 第五天 迪拜
主要景点：迪拜博物馆 dubai mall

迪拜博物馆，不大的一个博物馆，主要介绍了以前阿拉伯人的游牧采珠等农业活动和其他手工业活动，可以简单看下，里面有个小的纪念品商店，不便宜，但支持支付宝。

“王府家宴”参观吃中餐，参标比较高，所以吃得不错，菜的分量很足，加上早上10点才出门，早饭都没有消化，所以没吃完。不足的是：鱼虾蟹不新鲜，冷冻时间太长了，肉感觉都粘了。

* 第六天 回家
当地时间早6:00到达香港机场，过关办理手续等。

* 总结：
  迪拜那边的水很清澈，不管是海边还是运河。

  出国几次，还是感觉国内好，互联网的商业环境完爆国外。希望以后国内能把自然环境维护好。
