# -*- coding:utf-8-*-
#+TITLE: modules
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 概述

  模块是相关的 Go 软件包的集合。

  模块是源代码交换和版本控制的单元。

  go 命令直接支持使用模块，包括记录和解决模块间依赖。

  模块取代了旧的基于 GOPATH 的方法来指定构建使用的源代码。


** Module support

   The go command includes support for Go modules. Module-aware mode is active by default whenever a go.mod file is found in the current directory or in any parent directory.

   The quickest way to take advantage of module support is to check out your repository, create a go.mod file (described in the next section) there, and run go commands from within that file tree.

   For more fine-grained control, the go command continues to respect a temporary environment variable, GO111MODULE, which can be set to one of three string values: off, on, or auto (the default).

   If GO111MODULE=on, then the go command requires the use of modules, never consulting GOPATH. We refer to this as the command being module-aware or running in "module-aware mode".

   If GO111MODULE=off, then the go command never uses module support. Instead it looks in vendor directories and GOPATH
to find dependencies; we now refer to this as "GOPATH mode."

   If GO111MODULE=auto or is unset, then the go command enables or disables module support based on the current directory.
Module support is enabled only when the current directory contains a go.mod file or is below a directory containing a go.mod file.

   In module-aware mode, GOPATH no longer defines the meaning of imports during a build, but it still stores downloaded dependencies (in GOPATH/pkg/mod) and installed commands (in GOPATH/bin, unless GOBIN is set).

* Defining a module

  A module is defined by a tree of Go source files with a go.mod file in the tree's root directory. The directory containing the go.mod file is called the module root. Typically the module root will also correspond to a source code repository root (but in general it need not).

  The module is the set of all Go packages in the module root and its subdirectories, but excluding subtrees with their own go.mod files.

  The "module path" is the import path prefix corresponding to the module root.

  The go.mod file defines the module path and lists the specific versions of other modules that should be used when resolving imports during a build, by giving their module paths and versions.

  For example, this go.mod declares that the directory containing it is the root of the module with path example.com/m, and it also declares that the module depends on specific versions of golang.org/x/text and gopkg.in/yaml.v2:

  #+BEGIN_SRC go
module example.com/m

require (
	golang.org/x/text v0.3.0
	gopkg.in/yaml.v2 v2.1.0
)
  #+END_SRC


  The go.mod file can also specify replacements and excluded versions that only apply when building the module directly; they are ignored when the module is incorporated into a larger build. For more about the go.mod file, see 'go help go.mod'.

  To start a new module, simply create a go.mod file in the root of the module's directory tree, containing only a module statement.

  The 'go mod init' command can be used to do this:
  #+BEGIN_SRC sh
go mod init example.com/m
  #+END_SRC


  In a project already using an existing dependency management tool like godep, glide, or dep, 'go mod init' will also add require statements matching the existing configuration.

  Once the go.mod file exists, no additional steps are required: go commands like 'go build', 'go test', or even 'go list' will automatically add new dependencies as needed to satisfy imports.

** The main module and the build list

   The "main module" is the module containing the directory where the go command is run. The go command finds the module root by looking for a go.mod in the current directory, or else the current directory's parent directory, or else the parent's parent directory, and so on.

   The main module's go.mod file defines the precise set of packages available for use by the go command, through require, replace, and exclude statements. Dependency modules, found by following require statements, also contribute to the definition of that set of packages, but only through their go.mod files' require statements: any replace and exclude statements in dependency modules are ignored. The replace and exclude statements therefore allow the main module complete control over its own build, without also being subject to complete control by dependencies.

   The set of modules providing packages to builds is called the "build list". The build list initially contains only the main module. Then the go command adds to the list the exact module versions required by modules already on the list, recursively, until there is nothing left to add to the list. If multiple versions of a particular module are added to the list, then at the end only the latest version (according to semantic version ordering) is kept for use in the build.

   The 'go list' command provides information about the main module and the build list. For example:
   #+BEGIN_SRC sh
go list -m              # print path of main module
go list -m -f={{.Dir}}  # print root directory of main module
go list -m all          # print build list
   #+END_SRC


** Maintaining module requirements

   The go.mod file is meant to be readable and editable by both programmers and tools. The go command itself automatically updates the go.mod file to maintain a standard formatting and the accuracy of require statements.

   Any go command that finds an unfamiliar import will look up the module containing that import and add the latest version of that module to go.mod automatically. In most cases, therefore, it suffices to add an import to source code and run 'go build', 'go test', or even 'go list': as part of analyzing the package, the go command will discover and resolve the import and update the go.mod file.

   Any go command can determine that a module requirement is missing and must be added, even when considering only a single
package from the module. On the other hand, determining that a module requirement is no longer necessary and can be deleted requires a full view of all packages in the module, across all possible build configurations (architectures, operating systems, build tags, and so on). The 'go mod tidy' command builds that view and then adds any missing module requirements and removes unnecessary ones.

   As part of maintaining the require statements in go.mod, the go command tracks which ones provide packages imported directly by the current module and which ones provide packages only used indirectly by other module dependencies. Requirements needed only for indirect uses are marked with a "// indirect" comment in the go.mod file. Indirect requirements are automatically removed from the go.mod file once they are implied by other direct requirements. Indirect requirements only arise when using modules that fail to state some of their own dependencies or when explicitly upgrading a module's dependencies ahead of its own stated requirements.

   Because of this automatic maintenance, the information in go.mod is an up-to-date, readable description of the build.

   The 'go get' command updates go.mod to change the module versions used in a build. An upgrade of one module may imply upgrading others, and similarly a downgrade of one module may imply downgrading others. The 'go get' command makes these implied changes as well. If go.mod is edited directly, commands like 'go build' or 'go list' will assume that an upgrade is intended and automatically make any implied upgrades and update go.mod to reflect them.

   The 'go mod' command provides other functionality for use in maintaining and understanding modules and go.mod files. See 'go help mod'.

   The -mod build flag provides additional control over updating and use of go.mod.

   If invoked with -mod=readonly, the go command is disallowed from the implicit automatic updating of go.mod described above. Instead, it fails when any changes to go.mod are needed. This setting is most useful to check that go.mod does
not need updates, such as in a continuous integration and testing system. The "go get" command remains permitted to update go.mod even with -mod=readonly, and the "go mod" commands do not take the -mod flag (or any other build flags).

   If invoked with -mod=vendor, the go command loads packages from the main module's vendor directory instead of downloading modules to and loading packages from the module cache. The go command assumes the vendor directory holds correct copies of dependencies, and it does not compute the set of required module versions from go.mod files. However, the go command does check that vendor/modules.txt (generated by 'go mod vendor') contains metadata consistent with go.mod.

   If invoked with -mod=mod, the go command loads modules from the module cache even if there is a vendor directory present.

   If the go command is not invoked with a -mod flag and the vendor directory is present and the "go" version in go.mod is 1.14 or higher, the go command will act as if it were invoked with -mod=vendor.

** Pseudo-versions

   The go.mod file and the go command more generally use semantic versions as the standard form for describing module versions, so that versions can be compared to determine which should be considered earlier or later than another.

   A module version like v1.2.3 is introduced by tagging a revision in the underlying source repository. Untagged revisions can be referred to using a "pseudo-version" like v0.0.0-yyyymmddhhmmss-abcdefabcdef, where the time is the commit time in UTC and the final suffix is the prefix of the commit hash. The time portion ensures that two pseudo-versions can be compared to determine which happened later, the commit hash identifes the underlying commit, and the prefix (v0.0.0- in this example) is derived from the most recent tagged version in the commit graph before this commit.

   There are three pseudo-version forms:

   + vX.0.0-yyyymmddhhmmss-abcdefabcdef is used when there is no earlier versioned commit with an appropriate major version before the target commit. (This was originally the only form, so some older go.mod files use this form even for commits that do follow tags.)
   + vX.Y.Z-pre.0.yyyymmddhhmmss-abcdefabcdef is used when the most recent versioned commit before the target commit is vX.Y.Z-pre.
   + vX.Y.(Z+1)-0.yyyymmddhhmmss-abcdefabcdef is used when the most recent versioned commit before the target commit is vX.Y.Z.

   Pseudo-versions never need to be typed by hand: the go command will accept the plain commit hash and translate it into a pseudo-version (or a tagged version if available) automatically. This conversion is an example of a module query.

** Module queries

   The go command accepts a "module query" in place of a module version both on the command line and in the main module's go.mod file. (After evaluating a query found in the main module's go.mod file, the go command updates the file to replace the query with its result.)

   A fully-specified semantic version, such as "v1.2.3", evaluates to that specific version.

   A semantic version prefix, such as "v1" or "v1.2", evaluates to the latest available tagged version with that prefix.

   A semantic version comparison, such as "<v1.2.3" or ">=v1.5.6", evaluates to the available tagged version nearest to the comparison target (the latest version for < and <=, the earliest version for > and >=).

   The string "latest" matches the latest available tagged version, or else the underlying source repository's latest untagged revision.

   The string "upgrade" is like "latest", but if the module is currently required at a later version than the version "latest" would select (for example, a newer pre-release version), "upgrade" will select the later version instead.

   The string "patch" matches the latest available tagged version of a module with the same major and minor version numbers as the currently required version. If no version is currently required, "patch" is equivalent to "latest".

   A revision identifier for the underlying source repository, such as a commit hash prefix, revision tag, or branch name, selects that semantic version, the query evaluates to that semantic version. Otherwise the query evaluates to a pseudo-version for the commit.

   Note that branches and tags with names that are matched by other query syntax cannot be selected this way. For example, the query "v2" means the latest version starting with "v2", not the branch named "v2".

   All queries prefer release versions to pre-release versions. For example, "<v1.2.3" will prefer to return "v1.2.2"
instead of "v1.2.3-pre1", even though "v1.2.3-pre1" is nearer to the comparison target.

   Module versions disallowed by exclude statements in the main module's go.mod are considered unavailable and cannot
be returned by queries.

   For example, these commands are all valid:
   #+BEGIN_SRC sh
go get github.com/gorilla/mux@latest    # same (@latest is default for 'go get')
go get github.com/gorilla/mux@v1.6.2    # records v1.6.2
go get github.com/gorilla/mux@e3702bed2 # records v1.6.2
go get github.com/gorilla/mux@c856192   # records v0.0.0-20180517173623-c85619274f5d
go get github.com/gorilla/mux@master    # records current meaning of master
   #+END_SRC


** Module compatibility and semantic versioning

   The go command requires that modules use semantic versions and expects that the versions accurately describe compatibility: it assumes that v1.5.4 is a backwards-compatible replacement for v1.5.3, v1.4.0, and even v1.0.0.
More generally the go command expects that packages follow the "import compatibility rule", which says:

   "If an old package and a new package have the same import path, the new package must be backwards compatible with the old package."

   Because the go command assumes the import compatibility rule, a module definition can only set the minimum required version of one of its dependencies: it cannot set a maximum or exclude selected versions. Still, the import compatibility rule is not a guarantee: it may be that v1.5.4 is buggy and not a backwards-compatible replacement for v1.5.3. Because of this, the go command never updates from an older version to a newer version of a module unasked.

   In semantic versioning, changing the major version number indicates a lack of backwards compatibility with earlier versions. To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element.

   For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2, and packages in that module would use that path as their import path prefix, as in example.com/m/v2/sub/pkg. Including the major version number in the module path and import paths in this way is called "semantic import versioning". Pseudo-versions for modules with major
version v2 and later begin with that major version instead of v0, as in v2.0.0-20180326061214-4fc5987536ef.

   As a special case, module paths beginning with gopkg.in/ continue to use the conventions established on that system: the major version is always present, and it is preceded by a dot instead of a slash: gopkg.in/yaml.v1 and gopkg.in/yaml.v2, not gopkg.in/yaml and gopkg.in/yaml/v2.

   The go command treats modules with different module paths as unrelated: it makes no connection between example.com/m and example.com/m/v2. Modules with different major versions can be used together in a build and are kept separate by the fact that their packages use different import paths.

   In semantic versioning, major version v0 is for initial development, indicating no expectations of stability or backwards compatibility. Major version v0 does not appear in the module path, because those versions are preparation for v1.0.0, and v1 does not appear in the module path either.

   Code written before the semantic import versioning convention was introduced may use major versions v2 and later to describe the same set of unversioned import paths as used in v0 and v1. To accommodate such code, if a source code repository has a v2.0.0 or later tag for a file tree with no go.mod, the version is considered to be part of the v1 module's available versions and is given an +incompatible suffix when converted to a module version, as in v2.0.0+incompatible. The +incompatible tag is also applied to pseudo-versions derived from such versions, as in v2.0.1-0.yyyymmddhhmmss-abcdefabcdef+incompatible.

   In general, having a dependency in the build list (as reported by 'go list -m all') on a v0 version, pre-release version, pseudo-version, or +incompatible version is an indication that problems are more likely when upgrading that dependency, since there is no expectation of compatibility for those.

   See https://research.swtch.com/vgo-import for more information about semantic import versioning, and see https://semver.org/ for more about semantic versioning.

** Module code layout

   For now, see https://research.swtch.com/vgo-module for information about how source code in version control systems is mapped to module file trees.

** Module downloading and verification

   The go command can fetch modules from a proxy or connect to source control servers directly, according to the setting of the GOPROXY environment variable (see 'go help env'). The default setting for GOPROXY is "https://proxy.golang.org,direct", which means to try the Go module mirror run by Google and fall back to a direct connection if the proxy reports that it does not have the module (HTTP error 404 or 410). See https://proxy.golang.org/privacy for the service's privacy policy.

   If GOPROXY is set to the string "direct", downloads use a direct connection to source control servers. Setting GOPROXY to "off" disallows downloading modules from any source. Otherwise, GOPROXY is expected to be a comma-separated list of the URLs of module proxies, in which case the go command will fetch modules from those proxies. For each request, the go command tries each proxy in sequence, only moving to the next if the current proxy returns a 404 or 410 HTTP response. The string "direct" may appear in the proxy list, to cause a direct connection to be attempted at that point in the search. Any proxies listed after "direct" are never consulted.

   The GOPRIVATE and GONOPROXY environment variables allow bypassing the proxy for selected modules. See 'go help module-private' for details.

   No matter the source of the modules, the go command checks downloads against known checksums, to detect unexpected changes in the content of any specific module version from one day to the next. This check first consults the current module's go.sum file but falls back to the Go checksum database, controlled by the GOSUMDB and GONOSUMDB environment variables. See 'go help module-auth' for details.

   See 'go help goproxy' for details about the proxy protocol and also the format of the cached downloaded packages.

** Modules and vendoring

   When using modules, the go command typically satisfies dependencies by downloading modules from their sources and using those downloaded copies (after verification, as described in the previous section). Vendoring may be used to allow interoperation with older versions of Go, or to ensure that all files used for a build are stored together in a single file tree.

   The command 'go mod vendor' constructs a directory named vendor in the main module's root directory that contains copies of all packages needed to support builds and tests of packages in the main module. 'go mod vendor' also creates the file vendor/modules.txt that contains metadata about vendored packages and module versions. This file should be kept consistent with go.mod: when vendoring is used, 'go mod vendor' should be run after go.mod is updated.

   If the vendor directory is present in the main module's root directory, it will be used automatically if the "go" version in the main module's go.mod file is 1.14 or higher. Build commands like 'go build' and 'go test' will load packages from the vendor directory instead of accessing the network or the local module cache. To explicitly enable vendoring, invoke the go command with the flag -mod=vendor. To disable vendoring, use the flag -mod=mod.

   Unlike vendoring in GOPATH, the go command ignores vendor directories in locations other than the main module's root directory.

* GoProxy
  因为网络原因，在国内有些 package 不能使用 =go get= 直接下载或者下载速度比较慢，比如 =golang.org/x/xx= ， 一般有两种方法：
  + 设置 http_proxy/https_proxy 让 go get 请求走代理。
  + 官方提供了 GoProxy 环境变量，目前公开的 GOPROXY 有：
    + goproxy.io
    + 七牛云提供的 [[https://github.com/goproxy/goproxy.cn/blob/master/README.zh-CN.md][goproxy.cn]]


  需要注意的是，Go 1.13 及后续版本中默认将 GOPROXY 设置为 https://proxy.golang.org， 国内无法使用这个源，需要手动改掉：
  #+BEGIN_SRC sh
go env -w GOPROXY="https://goproxy.cn,direct"
  #+END_SRC

* 子命令
  go mod 支持的子命令如下:
  + download: 下载 modules 到本地缓存
  + edit: 提供一种命令行交互修改 go.mod 的方式
  + graph: 将 module 的依赖图在命令行打印出来，其实并不是很直观
  + init: 初始化 modules，会生成一个 go.mod 文件
  + tidy: 清理 go.mod 中的依赖，会添加缺失的依赖，同时移除没有用到的依赖
  + vendor: 将依赖包打包拷贝到项目的 vendor 目录下，值得注意的是并不会将 test code 中的依赖包打包到 vendor 中。这种设计在社区也引起过几次争论，但是并没有达成一致。
  + verify: verify 用来检测依赖包自下载之后是否被改动过。
  + why: 解释为什么 package 或者 module 是需要，但是看上去解释的理由并不是非常的直观。


* RePlace
  replace 主要用来解决包名发生变动的问题。

  基于此操作， http://golang.org/x/ 不能下载的包，但是对应的包在 github 上面是有对应的目录，这个时候我们就可以将 go.mod 中的包进行 replace 操作。

  下面是一个 Beego 项目的 go.mod 的 replace 的示例。
  #+begin_example
replace golang.org/x/crypto v0.0.0-20181127143415-eb0de9b17e85 => github.com/golang/crypto v0.0.0-20181127143415-eb0de9b17e85
replace gopkg.in/yaml.v2 v2.2.1 => github.com/go-yaml/yaml v0.0.0-20180328195020
  #+end_example


* GOPRIVATE

  go 命令默认是从 proxy.golang.org 上的公共 Go 模块镜像下载模块。默认情况下，无论 package 来源如何，默认根据 sum.golang.org 上的公共 Go 校验和数据库来验证下载的模块。这些默认设置适用于公开可用的源代码。

  go 命令通过 GOPRIVATE 环境变量识别哪个模块是私有的（不可公开获得），因此不应使用代理或校验和数据库。该变量是模块路径前缀的逗号分隔的全局模式列表（按照 Go 的 path.Match 的语法）。例如：

  #+BEGIN_SRC sh
GOPRIVATE=*.corp.example.com,rsc.io/private
  #+END_SRC

  go 命令将路径前缀与任一模式匹配的任何模块视为私有模块，包括 =git.corp.example.com/xyzzy, rsc.io/private, and rsc.io/private/quux= 。

  其他工具使用也可通过 GOPRIVATE 环境变量识别非公共模块。例如，编辑器可以使用 GOPRIVATE 来决定是否将软件包导入超链接到 godoc.org 页面。

  为了对模块下载和验证进行细粒度控制，GONOPROXY 和 GONOSUMDB 环境变量接受相同类型的 glob 列表，并覆盖 GOPRIVATE 以分别决定是否使用代理和校验和数据库。

  例如，如果公司运行了为私有模块提供服务的模块代理，则用户可以使用以下命令配置 go：

  #+BEGIN_SRC sh
GOPRIVATE=*.corp.example.com
GOPROXY=proxy.example.com
GONOPROXY=none
  #+END_SRC

  这将告诉 go 命令和其他工具，以 =corp.example.com= 子域开头的模块是私有的，但是公司代理应该用于下载公共模块和私有模块，因为 GONOPROXY 已设置为不会匹配任何模块，覆盖 GOPRIVATE。

  =go env -w= 命令（请参阅“ go help env”）可用于为以后的 go 命令调用设置这些变量。

* GOSUMDB
  GOSUMDB 是一个环境变量， 的全称为 Go CheckSum Database，用来下载的包的安全性校验问题。包的安全性在使用 GoProxy 之后更容易出现，比如我们引用了一个不安全的 GoProxy pv 之后然后下载了一个不安全的包，这个时候就出现了安全性问题。对于这种情况，可以通过 GOSUMDB 来对包的哈希值进行校验。当然如果想要关闭哈希校验，可以将 GOSUMDB 设置为 off；如果要对部分包关闭哈希校验，则可以将包的前缀设置到环境变量中 GONOSUMDB 中，设置规则类似 GOPRIVATE。
