# -*- coding:utf-8-*-
#+TITLE: 减肥记录
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 肥胖的坏处
  体重指数 ：BMI= 体重（kg）/ 身高(m)/身高(m)

* 为什么减肥困难
  + 脂肪高热量和人体本能决定的。半小时的跑步也就能消耗 20-30 克脂肪。
  + 不能通过节食减肥：当热量摄入减少时，基础代谢也会下降，情绪不佳。

* 运动减肥的本质
  实现脂肪供能最大化。因此无论采取什么的运动方式，只有 *保持低强度运动* 才能使脂肪在运动中供能效率最高。另外著名运动生理学研究 Edward L.FOX 在《运动生理学》书中提出，在 *运动 30 分钟后，脂肪供能比例增加，糖供能比例下降的现象，也就是说脂肪开始大量消耗* 。[fn:1]

  高强度的间歇跑步可以实现跑后燃脂。[fn:1]

  合理减肥：每周瘦一斤。较大幅度的减肥通常意味这水分丢失和肌肉含量的下降，反弹也容易，身体伤害大。

  减肥的体重变化趋势：
  + 初期体重不变。刚开始运动使肌肉变得紧致以及人体对于运动的发生相应的代谢反应。
  + 一段时间后体重明显下降
  + 遭遇瓶颈下降缓慢。

* 制定目标
  BMI = 85/1.72/1.72 = 28.7，属于肥胖，减肥目标保持在 22，对应的体重 65kg。

  无氧和有氧运动交替

* 饮食
+ 跑步后坚决拒绝含糖饮料
+ 拒绝高糖高脂食物
+ 适当控制主食
+ 适当控制水果
+ 选择优质健康食物
+ 七成饱
+ 吃饭慢些
+ 大餐之后青菜稀饭

* 跑步
  跑步：应该是建议活动量的 1 倍以上，即至少跑 40 分钟，或快走 1 小时。

  初跑者应该从快走、走跑结合开始，获得良好的运动体验，循序渐进。

  运用时间尽可能拉长是有好处的。

  不要太在意跑步后体重下降，十有八九是脱水造成的。

  跑步要和力量训练有机结合：
  + 跑步可以瘦，但是不能让人强壮。
  + 力量训练可以增加基础代谢。

  消耗脂肪最多：60%-75% 的最大心率。

  最大心率 = 220-年龄。

  跑不消耗脂肪最多的 （220-32） × 75% = 141.

  减肥快走 5.5 到 6 公里每小时。

* 力量

* 做记录

* Footnotes

[fn:1] https://www.zhihu.com/question/29603390/answer/565362676
