# -*- coding:utf-8-*-
#+TITLE: wireshark 数据包分析实战（2nd）
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com
#+OPTIONS: num:nil

* 第一章 数据包分析技术与网络基础

** 1.2.4 网络硬件
   集线器是工作在 OSI 参考模型物理层上的转发设备。集线器是半双工模式，广播全部流量。

   交换机工作在 OSI 参考模型的数据链路层上，直接发送数据到目的计算机端口。

   路由器工作在 OSI 参考模型的第三层。

** 1.3.1 广播流量
   并不是所有的广播流量都是以相同的方式构建的，而是包括第二层广播流量和第三层广播流量两种主要形式。

   再通过多个集线器或交换机链连接多种媒介的大型网络中，广播数据包将被从一个交换机中继到另一个交换机上，从而传输到网络连接的所有网段上。
* 第二章 监听网络线路

* 第三章 wireshark 入门
** 3.4 wireshark 初步入门
   mint 使用 =apt install -y wireshark= 安装后，捕获数据包遇到错误：
   #+BEGIN_QUOTE
couldn't run /usr/bin/dumpcap in child process: Permission Denied.
   #+END_QUOTE
   需要执行以下命令：
   #+BEGIN_SRC
sudo dpkg-reconfigure wireshark-common
   #+END_SRC
   选择 "YES" 。然后添加用户到 wireshark 用户组：

   #+BEGIN_SRC sh
sudo adduser $USER wireshark
   #+END_SRC
   重新登录后，打开 wireshark 就可以抓包了。

* 第四章 玩转捕获数据包
** 4.1 使用捕获文件
   可以将捕获文件进行合并。（使用情景？）

** 4.2 分析数据包
   + 查找，可以通过过滤器、十六进制数、字符串
   + 标记
   + 打印
** 4.3 设定时间格式和相对参考

** 4.4 设定捕获选项
   + 捕获设定
   + 捕获文件设定
   + 捕获停止设定

** 4.5 使用过滤器
   wireshark 主要提供两种过滤器：
   + 捕获过滤器

     使用 BPF 语法：每个 *表达式* 包含一个或多个 *原语* 。每个原语包含一个或多个 *限定词* ，然后跟一个 ID 名字或者数字。

   + 显示过滤器

* 第五章 wireshark 高级特性

  主要介绍 wireshark 的 Analysis 和 statics 两个功能：

** 5.1 网络端点和会话
   可以很方便的来定位问题。

** 5.2 基于协议分层结构的统计数据
   用户统计整体网络情况。

** 5.3 名字解析

** 5.4 协议解析
   可以手动更改 packet 解析器。

** 5.5 跟踪 TCP 流
   查看一个交互序列。

** 5.6 数据包长度
   可以常看网络中一些异常（特殊）的 packet。

** 5.7 图形展示
   + IO 图，查看网络流量。
   + 双向时间图，查看 RTT。
   + 数据流图，查看端点间的数据流。

* 第六章 通用底层网络协议

* 第七章 常见高层网络协议

* 第八章 基础的现实世界场景

* 第九章 让网络不再卡

** 9.4 定位高延迟原因
   通过分析服务端和客户端三次握手协议以及第一次数据传输，定位网络问题。

* 第十章 安全领域的数据包分析

* 第十一章 无线网络数据包分析
