# -*- coding:utf-8-*-
#+TITLE: acme申请 Let’s Encrypt 泛域名 SSL 证书
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com


* 概述
  [[file:certbot-get-ssl-ca.org][《certbot申请 Let's Encrypt泛域名证书》]] 一文中介绍了使用 Let's Encrypte 官方客户端申请泛域名证书的方法，但是申请和续期过程需要手动介入，现在介绍一种更加自动化的方法。

  [[https://github.com/Neilpang/acme.sh][acme.sh]] 是一个实现了 acme 协议的脚本，可以从 Let's Encrypt 生成免费的 SSL 证书。

  以下所有步骤参照了[[https://github.com/Neilpang/acme.sh/wiki/%25E8%25AF%25B4%25E6%2598%258E][acme.sh官方wiki]]，由于脚本更新频繁，将来以下步骤可能不适合，请大家直接参考 wiki。

* 安装
  #+BEGIN_SRC
curl https://get.acme.sh | sh
  #+END_SRC
  将程序安装在 =~/.acme.sh/= 下。

  以后更新 acme 程序：
  #+BEGIN_SRC
acme.sh --upgrade
  #+END_SRC

* 申请证书
  添加 dns api 相关 key 和秘钥。
  #+BEGIN_SRC
export Ali_Key="ali-key"
export Ali_Secret="ali-secret"
  #+END_SRC
  会将秘钥信息保存在： =~/.acme.sh/account.conf= 中，方便下面申请证书和以后证书续期使用。

  申请证书：
  #+BEGIN_SRC sh
acme.sh --issue --dns dns_ali -d panghuli.cn -d *.panghuli.cn
  #+END_SRC
  该命令会将申请的证书放在 =~/.acme.sh/panghuli.cn/= 下。

  该命令会添加定时任务，自动检测证书是否过期，并且续期。
  #+BEGIN_SRC sh
crontab -l
50 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
  #+END_SRC

  列出已经申请的证书信息：
  #+BEGIN_SRC sh
./acme.sh --list
  #+END_SRC

* 安装证书
  前面证书生成以后，接下来需要把证书 copy 到真正需要用它的地方.

  注意，默认生成的证书都放在安装目录下: ~/.acme.sh/, 请不要直接使用此目录下的文件，例如：不要直接让 nginx/apache 的配置文件使用这下面的文件。这里面的文件都是内部使用，而且目录结构可能会变化.

  正确的使用方法是使用 --installcert 命令，并指定目标位置，然后证书文件会被 copy 到相应的位置， 例如:

  #+BEGIN_SRC sh
acme.sh --installcert  -d  panghuli.cn  -d *.panghuli.cn \
        --ca-file /root/ssl/ca.cer \
        --cert-file /root/ssl/panghuli.cn.cer \
        --key-file   /root/ssl/panghuli.cn.key \
        --fullchain-file /root/ssl/fullchain.cer \
        --reloadcmd  "service nginx force-reload"
  #+END_SRC

  注意：如果是阿里云 ECS ，需要先使用 =service nginx start= 启动 nginx.service ,否则上面的命令会报错 “nginx.service is not active, cannot reload.”
