# -*- coding:utf-8 -*-
#+TITLE:2016 回顾及 2017 年计划
#+author:刘尚亮
#+email:phenix3443@gmail.com

* 2016
    回顾过去的 2016 年，有满足也有遗憾，总的来说达到了 2016 年的预订目标。
** 找了一份符合心意工作。

  从 2015 年 12 月 9 日入职迅雷至今，工作内容、个人成长、周围同事、薪资水平、公司福利等各方面自己都很满意。

  目前所在小组会员体系的开发维护工作，之前这方面是公司的核心业务，业务需求趋于稳定，目前主要工作是维护现有代码，对部分代码进行重构。我负责其中几个模块，同时自己推动产品线的工程代码文档化、服务 docker 化、以及开发过程的持续集成。

** 个人能力提升稍有遗憾。

  2016 年的主要侧重方向是提升 C++工程能力和调试能力。但在工作中，维护代码工作比较多，没有完整的开发一个大型的项目，C++工程能力提升不大。基本的调试技能掌握不少，对于高级调试技巧（多进程，多线程）还需要继续了解。

  另一方面，从 XXX 部门接手的 XXX 系统，从一开始的维护到最后自己完全重写过程中学了不少东西：openresty、python、mysql、docker。重要的是经历了一个产品从无到有，不断优化的过程，期间梳理知识点，建立技能树，工程文档化，和其他部门同事的沟通交流都感触良多。

** 遇到非常好的同事。
  + 感谢 XXX 部门魏同学在项目移交之后还能帮我解决线上问题。虽然交接不顺利，自己有时候有点怨气，但是好好想想原因还是在我。感谢你的大度和帮忙。

  + 感谢整个测试测试部门的同事，给你们添麻烦了。
	+ 感谢韩同学，刚开始开发 XXX 系统的时候真的是 bug 一堆，提测结果真的是我都不好意思看。感谢你不厌其烦的帮我测试 bug，没发过一次怨言。

	+ 感觉罗同学，虽然没什么需求交给你测试，但是你参与的几个项目评审流程，我也受益良多，平时其他的一些问题你也是有问必答，对业务产品非常清楚。

	+ 感谢杨同学，不管是 xxx 系统还是其他的业务模块，都尽心尽力帮我测试 bug，有几次还你周末还来加班，真是不好意思，你脾气也超级好。

	+ 感谢索同学，王同学，之前 xxx 系统第二版在你们这里测试的时候，虽然比较稳定，整个系统虽然不复杂，就是比较烦，但你们还是保证了测试结果，感谢你们的耐心。之前答应你们做的自动化测试一直没做完，真是抱歉，17 年一定做完并分享。

  + 感谢工作组里面的同事，虽然工作都是刚接手，但在一年的工作过程中，有问题相互解决，不推诿，负责任，都是靠谱的小伙伴。

  + 感谢刘老大的信任，能让我承担起更重更要的责任。

  + 感谢工作调动的飞哥和已经离职的丰哥，人虽然走了，但是只要有问题，一个电话过去还是有问必答。

  + 感谢运维部门的张同学，年底的一个任务上线几次都不顺利，也是多有麻烦。相信经过服务器迁移，以及服务 docker 化之后，上线任务会更加顺利。

  + 感谢其他部门合作过的同事，没有你们的协助，过去一年的工作也不会这么顺利。

* 2017

  今年的目标是成为初级架构师（软技能）和全栈工程师（硬技能）。主要内容：

** 培养大局观（架构师）
   去年的工作主要是个人工程能力（写代码、调试）的提升，对产品线整体运营情况了解不足，导致无法从宏观上了解业务需求，解决问题的时候一些观点过于片面，不利于自己大局观的培养和领导力的锻炼。

   今年将会把注意力更多放在整个高速业务架构上，从整体观察业务现状，并进行改进。

   将会接触和学习更多架构方面的知识，并实践于工作当中。

** 整理技能树（全栈）
   由于之前工作经历关系，对于一些基础知识的掌握和应用有很大不足，主要体现在个人知识体系和工程能力方面，尤其是后者，这个在 2015 年求职经历中劣势尤为明显。今年将继续进行知识系统化的工作，要整理，要对比，要举一反三，要有产出。
*** 整理编程语言
	+ Python（已完成）
	+ C++
	+ Lua
	+ C
	+ Java
	+ Lisp（Emacs）
	+ Ruby（信息安全）

	每种编程语言都将会产出两个系列的文档：
	+ 读书笔记

	  阅读各种语言经典的读书笔记，达到把书读薄的目的。

	+ 听说你会 xxx

	  该系列将整理和总结该语言的细节知识点，主要是面试的知识点和实用的小技巧，不归纳奇技淫巧的花哨用法。

*** 刷 leetcode

	算法是一个好的工程师必备的技能，目前已经荒废了。要通过刷 leetcode 保持算法能力和抽象解决问题的能力，同时编写代码的过程中实践各种编程语言。

*** 英语能力

	重点锻炼自己的写和口语能力，这样能参与到 github 上面的讨论当中。

** 工程自动化

   继续推动产品线产品的工程自动化，包括：

   + 代码编写

	 开发过程中引入代码检查工具，类似 pycheck，pylint 等工具，保证代码的标准化和对 bug 的静态检查。

   + 代码发布

	 使用 cmake 等自动化编译工具，直接生成要发布的源码包。

   + 自动化测试

	 开发侧引入自动化测试方案，保证每次提测之前的代码都是经过单元测试和集成测试，减少由于功能修改导致的副作用。

   + 服务 docker 化

	 使用 docker 部署线上服务，减少项目对操作系统的依赖。

   + 持续集成

	 开发过程中多次迭代，持续集成，为下一步的持续发布做准备。

   + 日志处理

	 引入 ELK 等日志处理系统，能够实时观察系统的运行情况。


** 把握行业前沿

   在做好上面工作的同时，也要了解行业的热点，对这些热点要做到：
   + 了解行业需求，对热点有基本认识。
   + 了解热点对应的岗位划分以及薪资情况，选择一个合适方向入门。
   + 将入门知识应用到实际中，有产出。

   今年主要跟踪：

*** 大数据

	大数据是目前行业比较火的话题，初步设想用大数据能监控做到会员业务状态的实时变更，改进自己开发的 xxx 系统。

*** 信息安全入门
	信息安全一直是自己比较感兴趣的方面，也一直想从事这方面的工作，但阴差阳错一直没有机会。今年希望能够学会 metasploit，进行简单的网络入侵测试。

** 移动端开发

   移动端开发是一个全栈工程师不可缺少的技能，今年对 android 和 ios 先有一个基本的入门，开发一款抢红包的 app 作为实践项目。

*** android 开发入门

*** IOS 开发入门
	使用 swift 语言。

* 健身

  现在上了年纪了，身体感觉素质越来越差，要加强身体锻炼。要把一直说的减肥落实下去。本来 16 年夏天开始跑步的时候想给大家吹个 nb 的，结果现在也不好意思说了。三十而立，自己的承诺首先要对得起自己。

** 跑步

** 游泳
   办了的游泳卡要用起来。
