# -*- coding:utf-8 -*-
#+title:Resilio
#+author:刘尚亮
#+email: phenix3443@gmail.com

* 概述
  Resilio Sync（以前称为 BitTorrent Sync）是 Resilio，Inc.发布的免费，快速，p2p 文件共享和同步工具。它可用于 Linux，Mac，FreeBSD，Windows，Android，iOS 和 NAS 设备。

* 安装
  各平台使用软件包进行安装，Linux 安装指南 https://help.resilio.com/hc/en-us/articles/206178924， linux 上的软件安装有点问题，“http://linux-packages.resilio.com/resilio-sync/key.asc” 这个文件下载不下来

** Windows & Mac

** Linux[fn:1]
   ubuntu 上 resilio 使用 web 作为 gui 界面，生成示例配置文件：
   #+BEGIN_SRC sh
rslsync --dump-sample-config > resilio.conf
   #+END_SRC

   编辑配置文件 resilio.conf
   #+BEGIN_SRC json
{
   "device_name": "phenix-ali-vps",

    /* storage_path dir contains auxilliary app files if no storage_path field: .sync dir created in current working directory */
   "storage_path" : "/home/phenix/.sync",

   /* use UPnP for port mapping */
   "use_upnp" : true,

   /* limits in kB/s. 0 - no limit */
   "download_limit" : 0,
   "upload_limit" : 0,

  /* directory_root path defines where the WebUI Folder browser starts (linux only). Default value is / */
  "directory_root" : "/home/phenix/resilio_sync/",
  "webui" :
  {
    "listen" : "127.0.0.1:8888" // remove field to disable WebUI
  }
}
   #+END_SRC

   启动服务：
   #+BEGIN_SRC sh
rslsync --config resilio.conf
   #+END_SRC

   服务以守护程序运行，Resilio Sync 守护程序将侦听 =resilio.conf= 配置文件中指定的 =127.0.0.1:8888= 。现在，可以在 Web 浏览器地址栏输入 =https://127.0.0.1:8888= 访问 Resilio Sync Web UI。

   然后将被要求设置用户名和密码来保护 Web UI。

** linux 服务端
   如果不想直接对外暴露 resilio 的端口，需要使用 nginx 做反向代理，nginx 配置文件：resilio.proxy.nginx.conf
   #+BEGIN_SRC nginx
server {
    listen 80;
    server_name resilio.your-domain;

    access_log /var/log/nginx/resilio.access.log;
    error_log /var/log/nginx/resilio.error.log;
    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
   #+END_SRC
   由于 vps 服务端部署好之后，没办法通过 web gui 设置密码，所以需要修改配置文件， =/etc/resilio-sync/config.json=
   #+BEGIN_SRC json
{
    "storage_path" : "/var/lib/resilio-sync/",
    "pid_file" : "/var/run/resilio-sync/sync.pid",

    "webui" :
    {
        "listen" : "127.0.0.1:8888",
        "login":"username",
        "password":"password"
    }
}
   #+END_SRC
   然后就可以通过 http://resilio.your-domain/gui 进行访问了，要注意，此时 *只能通过 http 进行访问* 。

*** 配置 https 进行访问
    给 resilio.your-domain 申请好阿里云免费的 HTTPs 证书后，修改 resilio.proxy.nginx.conf 文件。
    #+BEGIN_SRC nginx
server {
    listen 443 ssl;
    server_name resilio.your-domain;

    ssl_certificate /home/phenix/nginx/ssl/resilio.your-domain.pem;   # 替换成您证书的文件名。
    ssl_certificate_key /home/phenix/nginx/ssl/resilio.your-domain.key;   # 替换成您证书的密钥文件名。
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;  #使用此加密套件。
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;   #使用该协议进行配置。
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/resilio.access.log;
    error_log /var/log/nginx/resilio.error.log;

    location / {
        proxy_pass http://127.0.0.1:8888$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;                  # 重定向HTTP请求为HTTPs
    server_name resilio.your-domain;
    return 301 https://resilio.your-domain$request_uri;
}
    #+END_SRC
    现在可以通过 http(s)://resilio.your-domain 直接访问 resilio web gui 域名

** 配置文件启动[fn:5]
   在配置模式下运行同步使您可以在程序启动时应用预配置的参数。如果您需要在许多不同的计算机上应用相同的设置，这将非常有帮助。

* 存储文件夹(Storage Folder)[fn:6]
  Sync 使用存储文件夹保留其当前配置、辅助设置文件、共享数据库等的目录。您可以从此处收集支持人员请求的日志等信息。

  要更改桌面上版的默认位置，请在配置模式下[fn:5]运行同步。该文件夹的默认位置如下：
  + windows

    (will be Resilio Sync Service if you run Sync as service)
    #+begin_example
C:\Users\user_name\AppData\Roaming\Resilio Sync\
    #+end_example

    Sync running as service with LocalService:
    #+begin_example
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\Resilio Sync Service
    #+end_example

    Sync running as service with Local System:
    #+begin_example
C:\Windows\System32\config\systemprofile\AppData\Roaming\Resilio Sync Service
    #+end_example

  + Mac: /Users/user_name/Library/Application Support/Resilio Sync

  + Linux: ./sync near binary file or the current directory from which you launch Sync, or the path defined as "storage_path" if you run Sync in config mode

  + Linux packages:
    如果以 rslsync 身份启动：
    #+begin_example
/var/lib/resilio-sync
    #+end_example
    如果是当前用户启动：
    #+begin_example
/home/username/.config/resilio-sync/storage
    #+end_example

* 配置选项
** 通用(General)
   + 设备名称（device_name）
   + 默认文件夹位置(default folder location)：同步文件夹的默认存放位置。
   + 文件下载位置(default file location)：同步文件的默认存放位置。

** 身份(Identity)
   + 身份（Identity）[fn:3]

     身份是 Sync 中可用的最强大的功能之一。 Sync 要求在首次启动时提供身份名称。此名称将用于为您的 Sync 实例生成数字证书和随机指纹。这些将在以后与其他对等方的进一步连接时用到，看到指纹和其他名称，即可知道哪个 Sync 安装正在尝试连接至它们。

     使用许可证的 Sync Home Pro，Sync family Pro 和 Sync Business 允许多个设备通过同一标识链接在一起，它们展示在“我的设备（my devices）”列表中。通过将台式机，笔记本电脑和手机/平板电脑与 Sync 的 PKI 实施链接起来，您可以安全地将所有数据存储到任何设备上，而无需在云中创建帐户。首次打开 Sync 时创建的唯一数字证书具有文件夹权限，与其他设备建立连接并为 Sync Pro 授予许可。

   + 当前设备设置（this device setting）

     主要是选择设备同步模式：全同步，选择同步和不同步。[fn:4]

   + 设备列表（My Devices）

     显示在当前身份下链接的设备列表。

** 高级

* 使用[fn:7]
  resilio 可以用来同步文件夹和单个文件。

** 同步文件夹
*** 标准文件夹
*** 高级文件夹
*** 加密文件夹[fn:8]

    加密文件夹背后的整个想法是在不受信任的设备上拥有自己的对等设备，而不泄露任何数据。文件在传输前已加密，并且未在目标位置解密。

    例如，您可以将共享文件夹的副本添加到 VPS 或可供公众使用的设备，而不必担心其他人会读取或使用您的数据。此外，这个由 VPS 托管的对等方将全天 24 小时为您的数据播种，因此，如果其他对等方脱机，您仍然可以访问数据。

    系统将提示您选择一个文件夹，该文件夹中将存储来自源计算机的加密数据。使用系统的文件浏览器创建一个加密目录。

    注意：不要使用非空目录。已经存在的文件将不会被加密，并且只会被 Sync 忽略。如果您选择的目录中包含先前使用相同 F 键加密的文件，则这些文件仍将重新同步并移至存档。这将导致设备占用更多空间。

    您可以从备份计算机进一步共享此文件夹，尽管只能以加密格式共享。

**** 从加密的节点还原文件
     备份计算机上的加密文件夹（仅具有 F 键的文件夹）具有只读权限，“覆盖所有已更改的文件”选项始终处于激活状态，并且“选择性同步”不可用。这意味着，如果您或其他人删除此对等方上的文件，则 Sync 将从其他对等方再次下载它们，当然前提是它们在线且具有文件。

     加密的节点没有解密机制，因此无法解密文件。

     但是，在文件对等方源由于某种原因而失败的情况下，有机会从加密的备份对等方获取文件。为此，必须满足两个条件：
     1. 将 RW 和 RO（分别为 D-和 E-）键保存到此文件夹中的某个位置。
     2. 不要从加密节点上的同步中删除加密文件夹，以使数据库保持与最初创建的相同。

     在这种情况下，您可以使用主工作站上的 RW 键。它将连接到加密的节点并从中获取文件。 RW 密钥（D-密钥）可以解密它们。

     解密文件的另一种方法是在命令行界面中使用 command 在加密节点上本地执行操作
     #+BEGIN_SRC sh
--decrypt <secret> <db path> <encrypted folder> <output folder>
     #+END_SRC

     <secret>是源对等方的 RW 密钥。
     <db path>是数据库文件的完整路径。可以从 debug sync.log 中获知数据库名称：查找字符串“ started 周期性扫描”，然后在其中查看 shareID。数据库文件的名称末尾将带有这些。否则，请联系支持人员并将调试日志提交给他们。

** 同步文件[fn:9]
   需要注意的是：
   + 文件传输是单次单向的。这意味着如果共享文件发生更改，此传输将无效并且更改将不再同步。要同步更改的文件，请将它们再次添加到“同步”并生成新链接。
   + 接收文件的对等方可以进一步共享它们。他们不能更改链接的到期日期。
   + 如果链接已过期，则需要再次将文件添加到“同步”并生成新链接。
   + 如果目标对等方在选定目录中已经具有相同名称的文件，则 Sync 将在新目录中添加（1）索引并在 UI 中显示相应的消息。
   + 从 Sync UI 中删除文件不会将其从设备中删除。同样，从设备中删除文件不会从 Sync UI 中删除它，但是文件将不再上载。

** 重置 web UI 密码[fn:2]
   Sync 的 WebUI 受登录/密码保护，该密码是您在首次打开 WebUI 时定义的。这不是您的用户帐户的密码，也不与您可能拥有的任何其他帐户相关。这只是防止未经授权访问 Sync WebUI 的唯一保护措施。当网络浏览器会话结束时，同步的 cookie 会过期。

   如果您丢失/忘记了 WebUI 密码，则可以在同步存储文件夹中手动删除登录名和密码设置。请注意，这将导致“我的设备”列表中的设备重复。它不会影响同步共享，您可以忽略它。另外，偏好设置中的全局设置将重置为默认值。

   要重置登录名和密码设置，请按照下列步骤操作：
   1. 退出同步并关闭 WebUI。
   2. 转到同步存储文件夹。
   3. 找到并删除以下文件： settings.dat settings.dat.old
   4. 删除文件后，重新启动同步，打开 WebUI 并输入新的登录名和密码。

** 链接设备到同 Identity 下[fn:3]

* 购买许可证
  如果只是需要进行资源分享，不需要对分享对象的权限进行控制，免费版就足够了。

  如果需要在自己的多个设备之间同步资料，需要用到以下特性，需要购买 HOME one user 的许可证：
  + 多个设备之间自动同步，不需要通过 resilio 的二维码或者连接手动进行同步。
  + 需要对同步的文件（夹）进行选择同步。


  简而言之，如果只是分享资源，免费版就够了，如果想要不同设备间同步多个文件（夹），还是推荐买个授权。

* Footnotes

[fn:9] https://help.resilio.com/hc/en-us/articles/115000401010-Sharing-single-file

[fn:8] https://help.resilio.com/hc/en-us/articles/207370466

[fn:7] https://help.resilio.com/hc/en-us/articles/204755009-Sync-Main-View-Desktop-

[fn:6] https://help.resilio.com/hc/en-us/articles/206664690-Sync-Storage-folder#

[fn:5] https://help.resilio.com/hc/en-us/articles/206178884-Running-Sync-in-configuration-mode

[fn:4] https://help.resilio.com/hc/en-us/articles/205457775-Synchronization-Modes

[fn:3] https://help.resilio.com/hc/en-us/articles/205457815-Sync-Private-Identity-Linking-My-Devices

[fn:2] https://help.resilio.com/hc/en-us/articles/205450295-How-do-I-reset-my-WebUI-password-

[fn:1] https://www.linuxbabe.com/ubuntu/install-resilio-sync-ubuntu-16-04-16-10
