# -*- coding:utf-8-*-
#+TITLE: 自控力
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com
#+STARTUP: overview
#+OPTIONS: author:nil date:nil creator:nil timestamp:nil validate:nil num:nil


* 导言
  提高自控的有效途径在于，弄清自己如何失控，为何失控。

  自知之明是自控的基础，认识到自己的意志力存在问题，则是自控的关键。

  意志力挑战：
  + 逃避的事情（“我要做”的意志力挑战）：（提高效率）
  + 改掉的习惯（“我不要”的意志力挑战）：（拖延）
  + 重要的生活目标（“我想要”的意志力挑战）：（健康生活，高效工作）

* 什么是意志力
   意志力实际上是“我要做”，“我不要”，“我想要”三种力量。它们协同努力，让我们变成更好的自己。

   实践：思考更难的事情是什么？为什么会困难？当想到它的时候的感觉是什么？
   + 减肥为什么难？
   + 专注为什么难？

* 为什么需要意志力
   为了更好的团结合作，人们衍生出意志力来克服原始本能冲动。

   意志力挑战过程中获胜的关键，在于学会利用原始本能，而不是反抗这些本能。

   实践：回想意志力挑战中两个自我的对抗过程。

** 意识
   人类拥有意识：知道自己在做什么，以及为什么要这样做。

   在自控的过程中反思自己的行为，更加坚定自控。

   注意力分散的人更容易失控。 *所以需要锻炼自己的专注力*

   实践：思考一天中自己的行为，哪些行为自控，哪些失控。

* 如何锻炼意志力

** 意志力和生理有关
   本能和自控，应激反应和自控反应。

   自控的生理学指标：
   + 压力，交感神经，心率升高，心率变异度降低。
   + 自控，副交感神经，心率降低，心率变异度升高。

   心率变异度搞得人能更好的集中精力、更好的应对压力。

** 锻炼方法

*** 健康饮食
    未加工的食物。

*** 冥想
    实践：
    + 静坐
    + 注意呼吸，默念“呼吸”二字，走神时重新集中到呼吸上。
    + 感受呼吸，感受空气吸入呼出，胸腹的收缩扩张，弄清自己是怎么走神的。

*** 放慢呼吸
    每天进行 20 分钟放慢呼吸的练习，有助于提高心率变异度。

    实践：将呼吸频率降低到每分钟 4-6 次。

*** 锻炼
    锻炼能提高心率变异的基准线，从而改善意志力的生理基础。

*** 睡眠
    缺少睡眠会影响身体和大脑吸收葡萄糖，前额皮质因为能量不足会失去对大脑其他区域的控制。

    充足睡眠，补觉，打盹。

*** 放松
    自控需要消耗能量，试图控制所有思想、情绪和行为也会带来过重的生理负担。所以需要放松来进行调节。

    实践：生理放松 5-10 分钟。

* 意志力的极限
  意志力如同肌肉一样，也有极限。但是锻炼自控力能提升上限。

  自控需要消耗能量。人在饥饿的时候更愿意冒险。

  实践：
  + 保证食物身体有足够的食物，推荐低血糖饮食。
  + 锻炼意志力方法：控制自己以前不会去控制的小事。目的：养成习惯，关注自己正在做的事情。

  虚假疲惫，可能是大脑给出的一种保护信号。

  实践：当疲惫时，运用“我想要”的力量。

  如果想要增强自控力，就要考虑如何支撑住最疲劳的自己。

* 善行之后的恶行
  不是每次失控都是真正失去了意志力，有时，我们是有意识的选择了在诱惑面前屈服。

  “道德许可效应”：我们很容易的认为，纵容是对美德最好的奖励；而我们忘记了自己的目标，向诱惑屈服了。

  我们通常相信本能，只有当需要解释自己的判断时，我们才寻求逻辑。

  最能带给我们动力的事情是获得我们想要的，避开我们不想要的。而不是将某种行为到道德化。

  我们总是把进步当做放松的借口。

  实践：取消许可，牢记理由。当我们用善行给放纵做借口时，想想自己为什么能拒绝诱惑。

  透支明天：明天和今天毫无区别，当想改变行为时，试着减少行为的变化性，而不是减少某种行为。

  实践：今日事今日毕，不要透支明天。

  光环效应：当我们想要获得放纵许可的时候，我们会寻找一个美德暗示，为自己放弃抵抗做辩护。

  只要使你放纵的东西和是你觉得品德高尚的东西同时出现时，就会产生光环效应。

  当我们将意志力挑战看成衡量道德水平的标准时，善行就会允许我们做坏事，为了更好的自控，我们需要忘掉美德，关注目标和价值观。

* 错把渴望当成幸福
  多巴胺的作用是让我们追求快乐，而不是让我们快乐。

  示例：想占有某件东西。

  实践：区分是渴望占有，还是物品真的有用。

* 情绪低落导致屈服

  压力带来欲望，大脑把欲望和奖励系统联系在一起。

  有效的解压方法：锻炼，阅读，听音乐，散步，冥想。

  自我谅解会在破罐子破摔的时候不再放纵自己。

  自我批评会降低积极性和自控力，而且容易导致抑郁。自我同情则相反：自我同情的人更愿意承担责任，接受别人的反馈和建议。

  不要用“改变的承诺”，而不是“改变”来改善我们的心情。前者完不成容易导致更大的失落。

  乐观给我们动力，但少许的悲观能帮助我们走向成功。

  实践：预见失败其实是一种自我同情的方式，而不是自我怀疑的方式。
* 出售未来与及时行乐

* 意志力会传染

* “我不要”力量的局限性
