# -*- coding:utf-8-*-
#+TITLE: 杭州
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 准备工作
  1. 查询天气。

     旅游期间杭州晴天比较多，准备好帽子，防晒霜，擦汗用的毛巾。线路上有不少的水域和树林，我又比较怕蚊子，准备好驱蚊喷雾，电蚊香。

  2. 摄影装备。

     相机：索尼 a7m3 ，24-70 2.8 gm ， 35 1.4 g， 80 1.4。其中前两个镜头是兰拓租的，价格还算便宜，主要是想体验一下这两个镜头，准备生日的时候入手其中之一。大部分在使用 2470 拍摄，小河直街用 35 拍摄，80 没派上用场。最后打算还是入手一个 16-35 2.8 的吧，24 感觉有些场景拍不到，70 拍远景也比较尴尬，不长不短的。摄影新手，高手勿喷。

     iPhone x 主要给女朋友拍照，发朋友圈。

     背包：乐摄宝金刚 ProTactic 450，行程能够放下我的一机三镜，游览的时候带着一机一镜，还有一些清理工具，重新整理隔断，背包顶部放了充电宝，水果，吃的，3-4 瓶矿泉水，超大容量和良好的背负系统，背着压力也不大。


* 实际行程


** day1
   7:15-9:10 深圳飞杭州。

   去哪儿买的飞机票，因为赶大清早的飞机，为了不赶时间，直接前一天晚上在机场附近过夜，看了一下去哪儿机票订单推荐的 49 元格林豪泰宾馆，评价不咋样，换了另一家酒店。

   金鹏航空，行李不能免费托运，多花了 180 的行李费用，没有早餐，有这钱和体验，我乘坐别的航空公司的飞机了，体验差，拉入黑名单。而且七点半多才起飞，九点半多才降落，晚点了，怪不得准点率那么低。

   10:00-12:00 杭州萧山机场-花间堂（西溪龙舌嘴入口）。机场大巴西站线，在杭州汽车西站下，然后打车到花间堂，办理入住。

   12:00-14:00 西溪湿地对面印象城外婆家用餐。茶香鸡味道不错，龙井虾仁蘸料也不错，土豆泥一如既往，麻婆豆腐居然还是三块钱。

   14:00-17:00 乘车前往西湖，走之前准备的线路一（北山路-杨公堤-上香古道-茅家埠-浴鹄湾-太子湾）。途径招贤寺旧址，静逸别墅，润庐，新新饭店，在游览至玛瑙寺的时候开始下起小雨，因为快到结束时间了，简单游览，其实景色很不错，值得多花时间，圆形和拱形月门，白墙黑瓦，拍照很好看。

   17:00-20:00 北山路上肯德基用餐休息，餐后夜游对面的曲院风荷，小雨初歇，整个园区雾气蒙蒙。出园后走杨公堤，持伞夜游上香古道，途经各色凉亭，小桥，观茅家埠水景，黛色参天短歇，后走至龙井路的茅家埠公交站，滴滴回花间堂。

   22:00-24:00 两个人看异形（契约）和异形第三部

** day2
   9:00-12:00 花间堂吃早餐，和女朋友腻歪，躺椅发呆。

   12:00-17:00 走之前计划的线路三（灵隐寺-天竺三寺-杨梅岭-云栖竹径-浙大之江校区）。

   寺庙都没有开门，只能远远看看里面。

   在灵隐寺到天竺三寺的路上走了很久，吃了路边小店的藕粉和葱包烩。藕粉甜甜的，还不错。

   短歇后继续徒步只到法喜寺。途经杭州图书馆佛学分馆，入内参观。

   之后公交前往云栖竹径，但因预约满了进不去，继而前往之江校区，但不开放。

   饿了，然后打车去杭帮菜博物馆，东坡肉很不错，莼菜汤好吃，滑滑的，水里看到几只小的野鸭子，我还看到两个大的飞走了，野鸭子还真会飞，飞的不低。

   18:30-22:00 滴滴乘车前往太子湾，准备补前一天剩下的浴鹄湾，女朋友想看断桥，改夜走苏堤，至北山路，途经武松墓，苏小小墓，黄宾虹像，

   观平湖秋月，转西冷印社，楼外楼，白堤，上断桥。北山路出，出租车回花间堂。

** day3
   9:00-12:00 吃饭，腻歪，行李寄存前台，退房。

   12:00-14:00 西溪西区龙舌嘴入口-洪湖，游船，登步云塔，远眺西溪全景，看不到个啥，一片片都是树。

   14:00-18:00 西溪东区周家村入口-深潭口，乘船，上岸，走蒋村-河褚街-福堤，途径洪家祠堂，热气球，演武堂，施耐庵塑像，福堤，一路上认识花花草草。

   天目山路口已关闭，沿着西溪湿地健身绿道走了好长一段，到了中国湿地博物馆附近，准备吃完饭，发现花房私房菜和西溪别院都在附近。

   最后选择花房的 199 双人套餐，冰镇小龙虾味道很不错，带点点甜味，双头乌也不错，不肥腻，鱼肉质鲜嫩，米饭好吃，问了一下是甜米，女朋友淘宝已经下单。

   出门溜达着前往公交站回花间堂，这里因为修路，公交站有点远，建议直接打车，取行李打滴滴前往滨江亚朵网易严选酒店，洗漱睡觉，走路累死了。

   而且发现杭州高德地图上面的打车费用要比出租车便宜不少，有一次高德显示打车 40，出租车最后结算 60，没有黑杭州出租的意思，但是我后面都选择直接高德打车。

** day4

   8:00-11:00 吃早饭，睡回笼觉

   11:00-14:00 老大说加个班，心里。。。。由于加班，严重压缩了下午的行程，导致浏览的过程很匆忙。怨念。。。

   14:30-17:00 滴滴前往小河直街，路上找了一家小店，和女朋友吃了两份片儿川，要比酒店早餐做的好吃。

   前往小河直街，随便溜达，老街感觉还行。

   徒步前往拱宸桥，拱宸桥上远望，大运河河面宽阔，航船来往，河面两个不知道是什么雕塑。

   17:30-19:00 回亚朵酒店，和女朋友边同学吃饭，周家私房菜，杭州感觉很多私房菜的样子。

   女朋友同学开车机场送行，路上短暂停留钱塘江边，网易云音乐办公楼附近。

   整个行程就是这样了，剩一天在家修养。下面是出发前准备的线路攻略。

* 西湖线路一
  常规旅游线路，游客比较多。

  看点：名人故居，西湖十景。

  + 音乐喷泉
  + 中国美院南山校区
  + 民国名人故居
  + 柳浪闻莺
  + 长桥落日
  + 太子湾公园
  + 雷峰夕照
  + 南屏晚钟
  + 苏堤
  + 花港观鱼
  + 三潭印月
  + 苏堤春晓
  + 曲院风荷
  + 平湖秋月
  + 断桥


* 西湖线路二
  看点：名人故居，民国建筑，寺庙遗址，新旧西湖十景，各色凉亭。

  + 北山路

    北山路 3098 米的长街短巷里集中筑有一些近代优秀建筑，一边是山，一边是水，山与水的中间则是房子。它们与西湖互为辉映，相得益彰，被誉为杭州近代建筑博物馆。

    + 北山路 2-3 号，望海楼

    + 北山路 8 号，[[https://zh.wikipedia.org/wiki/%25E8%2592%258B%25E7%25BB%258F%25E5%259B%25BD%25E6%2597%25A7%25E5%25B1%2585_(%25E6%259D%25AD%25E5%25B7%259E)][蒋经国故居]]

      蒋经国旧居坐落于浙江省杭州市西湖区石函路 7 号，临近断桥，是浙江省文物保护单位。抗日战争胜利后曾为蒋经国和蒋方良之居，与蒋介石和宋美龄所居之澄庐隔湖相望。

      《照片》

    + 北山路 32 号，坚匏（pao，二声）别墅（又称小莲庄或小刘庄）

      这里的主人，是湖州南浔江南首富刘氏，清末民初中国最大的“房地产商”之一。在上海，刘氏家族开创了地产行业的半壁江山，如今人们看到的上海石库门、花园洋房都带有浓重的刘家印记。

      杭州北山街上的别墅，有一半都是刘家的产业。从清朝末年，到 1935 年，坚匏别墅的建造史整整持续了 23 年，成为第一个中西合璧的别墅。

      《外观照片》

      它门口的古井，用汉白玉雕制而成；养鱼的池塘，是天然形成；园中那座小亭，因为与西泠遥遥相对，被唤作“东泠”；在小小的院落中，嵌着一汪碧水，塘中养莲，从而诞生个别名，叫“小莲庄”。

      《古井照片》 《水池照片》

    + [[https://baike.baidu.com/item/%25E6%25B6%25A6%25E5%25BA%2590][润庐]]

      润庐建于 1932 年，当时的门牌是葛岭山路 2 号，润庐的第二个主人是著名金融家金润泉（1878-1954），被清政府封为三品官衔，成为浙江第二个红顶商人。从 1909 年任大清银行浙江分行行长起，到 1951 年底中国银行杭州分行撤销为止，金润泉当了四十多年行长，扮演了四十多年主角，连任时间之长是空前的。辛亥革命后，历任中国银行总行营业部经理、中国银行杭州分行行长、杭州市商代会主席等。抗日战争时期，设法保存了中国银行资产。具有强烈的爱国主义情怀，在抗日救国等方面做了大量工作。新中国成立后，继续留任中国银行董事、分行经理、总行赴外稽核。从清末到新中国成立，金润泉一直掌管着浙江的金融大权，并在商贸、电力、教育、筑桥修路、交通等各个行业投入大量的资金。在中国近代金融史上，被誉为“金融界的常青树”。 润庐的“润”字也取自金润泉名字当中的“润”。

      《外观照片》

    + 北山路 34 号，如庐

      曾经是民国时期上海大商人林九如的私人住宅，后来被政府收购。如庐面对西湖，背靠宝石山，具体是建在靠近北山街的小山坡上。大门左侧有一位长型的石碑上隐约可以看到“如庐沉香堂”几个字。

      《外观照片》


    + 北山路 35 号，海盐馆

      杭州海盐馆位于西湖区北山路 35 号，面对着西湖，是杭州西湖边典型的明清风格的建筑体，该建筑体目前被顾家家居租用作为顾家家具集团高端会客场所，为园林式高端会所。内部含接待大厅、会议室、茶楼、办公区、包厢、客房及顾家样品展示区。

      《外观照片》

    + 北山路 36 号，省庐

      “省庐”，又叫做“竹隐楼”，建于民国初年，为仿西式建筑。

      《外观照片》

    + 北山路 38 号，秋水山庄

      秋水山庄是 20 世纪 30 年代我国报业巨子、上海《申报》报主史量才以他的爱妻沈秋水命名而建的江南庭院式建筑。面积约 200 平方米，四周有庭院，沿着北山路有围墙、铁门。秋水，原名沈慧芝，原为晚清上海滩的雏妓，后遇到了同样喜爱鼓琴的史量才，便以身相许伴随到了杭州。

      史量才随后因秋水的私人财务而得力购入《申报》《新闻报》，成为报业泰斗。然而，史量才又纳入外室女子一名，出于愧疚，为秋水在西湖葛岭旁买了别墅，即秋水山庄。如今秋水山庄是新新饭店的一部分，可以入住饭店，也可以在这里喝茶赏湖色。

      《外观照片》


    + 北山路 39-40 号，抱青别墅（又称抱青会馆）

      沿着北山街继续骑行，你一定会看见一幢赭红色的砖墙，拱形门串起一条走廊，这里便是百年老楼抱青别墅，也是北山街的标志一景。这座同样出自南浔富贵之家的别墅，30 年代时曾被改建成葛岭旅馆，成为当时西湖边最奢华的酒店。别墅为三层西式楼房，属于欧洲巴洛克建筑式样，而它的砖木结构、朱红色彩、老式黑瓦以及内部陈设，又留有中国传统建筑的痕迹。整幢建筑体现了近代西湖建筑承上启下、中西交汇的过渡特点。百岁高龄的抱青别墅现已转身成为杭州国画院美术馆。

      《外观照片》

    + 北山路 41-42 号，西湖博览会博物馆（首届西湖博览会会址）

      1929 年．第一界西湖博览会在这里成功举办。在那个战火纷飞、动荡不堪的年代，历时 137 天的博览会吸引了 2000 多万人前来观看，着实是推动了当时萎靡不振的工业经济发展。如今的展馆是在原址上扩建而成，展示了西湖博览会的前世今生。

      《外观照片》

    + 北山路 43 号，王庄

      王庄建于 1926 年，占地面积 3.3 亩，西式主楼建筑面积 744.13 平方米，有房 29 间；另有中式平房 4 间，建筑面积 104.37 平房米。它最早的业主是北京李国筠，后转让给上海金融界知名人士王晓策，此宅便更名为王庄。

      王庄的建筑可圈可点，除了它的坐北朝南、依山面湖、中西合璧、宅院合一的特点外，它的建筑细部的艺术特征也颇有特色。

      一是它的青砖实叠南侧外墙上，大量采用了欧洲古典主义风格的爱奥尼克倚柱，不仅起到了承重作用，更是明显的外表装饰。

      《外观照片》

      二是带有各种雕饰和艺术加工的栏杆是其建筑细部的显著特征，瓶状或石柱形的欧式栏杆成为此屋的重要标记。

      《栏杆照片》

      三是该建筑设有宽大的阳台、走廊、台阶、屋顶平台等开放与半开放的建筑空间，它们既是居者的活动空间，也是观景赏色的佳处。

      《阳台屋顶》

    + [[https://baike.baidu.com/item/%25E7%258E%259B%25E7%2591%2599%25E5%25AF%25BA][玛瑙寺]]（连横纪念馆）

      葛岭路 17 号的一处原佛教讲寺，始建于五代后晋开运三年（946），北宋治平二年（1065）改今额。寺院旧在孤山玛瑙坡，并因其址而得名，南宋绍兴二十二年（1152）迁至今址，原址改作延祥观。今存建筑为清末至民国时重修，主要分前后两院，中轴线上依次为山门三间、月洞门、大殿五间（现存遗址）和后殿五间，东西有厢房数间，旁有园林，为杭州寺院园林的典型代表。台湾历史学家连横曾在 1926-1927 年居住于此并研究整理文史资料，2008 年 12 月作为连横纪念馆对外开放[2]，现已不再作为宗教建筑使用。

      《月洞门照片》《白墙照片》


    + 北山路 44-45 号，[[https://baike.baidu.com/item/%25E8%258F%25A9%25E6%258F%2590%25E7%25B2%25BE%25E8%2588%258D][菩提精舍]]

      菩提精舍，建于 1926 年，为丁甘仁等 24 位沪浙商界名流，以佛教信徒的居士身份筹款建造，以此为念经礼佛修身之地。

    + 北山路 54 号，[[https://baike.baidu.com/item/%25E6%2598%25A5%25E6%25B6%25A6%25E5%25BA%2590][春润庐]]

      春润庐是宋春舫和其好友朱润生共同建造的，庐内有两座带有壁炉的别墅：外面的那座是朱润生的，可以称之为“润庐”；里面的那座是宋春舫的，也可以称之为“春庐”。春润庐之名就是各取两位业主姓名中的一个字而成。

      宋春舫（1892-1938）是浙江吴兴人，早年留法，我国早期著名戏剧家及法国文学专家，曾先后在北京大学、清华大学任教，著有《宋春舫论戏剧》；家中富有，在上海及青岛均有房地产。朱润生为宋氏亲戚，银行家。

      当时如果有北大著名的教授去杭州 , 宋春舫都邀请他们前去居住 。 蔡元培曾是春润庐较早的房客。1927 年，两位北大教授马寅初和谭熙鸿来杭州任教，他们都是宋春舫的老友，所以都把家安在了春润庐。春润庐便成了不挂牌的北京大学招待所。徐宝璜、林风眠、张歆海等著名学者都曾携眷住过此庐，至于来春润庐拜访的名人就更多了 ，

      《外观照片》

    + 晓风书屋

      很小的一个书店，有手办、香囊等小东西。

    + 北山路 58 号，[[https://zh.wikipedia.org/wiki/%25E6%2596%25B0%25E6%2596%25B0%25E9%25A5%25AD%25E5%25BA%2597][新新饭店]]

      杭州新新饭店由东楼（前身为何庄）、西楼（始建于 1912 年孤云草舍）、中楼（始建于 1922 年）、秋水山庄（始建于 1932 年）和北楼等楼群组成。西楼、中楼、秋水山庄被列入近代历史文物保护建筑。

      尽管这家饭店的名字叫“新新”，资格却是够老的。饭店前身可追溯到 19 世纪 90 年代，由上海最早连锁企业“何锦丰洋广杂货号”老板何宝林，在东楼旧址上陆续建成中、西式楼房三幢，称为何庄。1909 年董锡赓发现商机，与何宝林之子何积藩合股在何庄开始接待宾客，1913 年设计完成英文名为“THE NEW HOTEL”、中文名为“新新旅馆”的店牌。

      《外观照片》

    + 北山路 60 号，招贤寺

      唐代招贤寺遗址。

      《外观照片》

    + 北山路 66 号，[[https://baike.baidu.com/item/%25E6%2581%25AF%25E5%25BA%2590][息庐]]

      为园林式别墅，园内池沼假山，花木扶疏，占地约 1 亩。园墅的东南边大门紧靠北山路，进门为一天井，天井正中是一幢三开间大殿，传统的大屋顶中式风格；大殿后又是一个天井，拾级而上，是一幢两层三开间精致的西式砖木小楼；小楼西边另有辅房四间。建筑面积 300 多平方米的息庐呈二进院落式布局，建筑层层递进，地基渐次抬高。前后两进房屋一中一西，一低一高，依山傍湖，坐北朝南，的确是休憩疗养的好去处，这也正因了息庐的名字：休息的房舍。

      《景观照片》

    + 北山路 69-71 号，[[https://baike.baidu.com/item/%25E9%259B%2586%25E8%2589%25BA%25E6%25A5%25BC][集艺楼]]

      集艺楼位于西湖区北山路 69、71 号，是一座建于 20 世纪 30 年代的砖木结构、钢窗蜡地的两层西式小楼。小楼依山面湖，坐北朝南，占地 0.5 亩，建筑面积 280 平方米，共有房 13 间。

    + 北山路 80 号，岳王庙

      岳庙，多称为岳王庙，位于西湖栖霞岭南麓，始建于南宋嘉定十四年（1221），初称“褒忠衍福禅寺”，明天顺间改额“忠烈庙”；因岳飞追封鄂王而称岳王庙，

      历代迭经兴废，现存格局于清代重建后形成，分为墓园、忠烈祠、启忠祠三部分。 墓园坐西向东，忠烈祠和启忠祠坐北朝南；岳王庙大门，正对西湖五大水面之一的岳湖，墓庙与岳湖之间，高耸着“碧血丹心”石坊，寄托炎黄子孙对爱国英雄的敬仰之情。现岳飞墓为全国重点保护文物。

    + 竹素园

      在岳坟西面，面积 2 万平方米。旧称湖山春社，为清浙督李卫建。凿池置石，构筑亭轩，栽培四时花木，引桃溪清流，屈曲环注，有曲水流觞之意。乾隆御书"竹素园"。今内通江南名石园。园内盆景假山，回廊迷离，修篁弄素，清新恬淡。

      《园林》

      《美景》

      《湖面》


    + 北山路 94 号，江南文学会馆（穗庐）

      也叫鲍庄，堂号“穗德堂”，是一座保存较完整的集住宅、祠堂、家坟于一体的山地园林式的花园别墅。

      鲍庄原主人鲍柏麟，广东人，在穗沪杭经营多种产业，家底甚厚。他所建造的这所穗庐，颇具家乡岭南风韵，亭尖和亭角是中式的而柱子是西式的，并且有向上升腾的含义，与西方通往天堂的含义有异曲同工之妙。

      从北山路沿山道拾级步入鲍庄，首先映入眼帘的是一座雕刻精美的砖饰门楼，气势不凡，门楣上书"穗庐"二字，落款为赵梅溪。进得门楼，有一古樟，树龄逾 300 年。树阴掩映中，一座两层三开间的西式别墅赫然入目，此楼砖石垒基、天花吊顶、瓶饰栏杆、通天云梯，共 9 间房，225.95 平方米，另有平房 5 间半，134.5 平方米。

      出得院来，继续沿巨型石板铺就的山追上行，是鲍庄的后院，此地有祠堂一所，家坟一丘，石亭两座．都是依山而建，顺势而上，整个鲍庄占地 2.019 亩，始建于 1922 年，迄今已有 80 年历史。

    + 杨公堤北山街口自行车租赁点


  + 杭州花圃

    《花朵照片》

  + 郭庄

    郭庄位于中国浙江省杭州市西湖区杨公堤 28 号（原西山路卧龙桥北堍东 8 号）、北与曲院风荷公园相邻，为杭州古典园林的代表，园虽不大，但布置紧凑，结构巧妙，其中的假山楼阁具有典型的江南园林特色。

    该园由杭州丝绸商宋端甫始建于清咸丰年间[注 1]，名端友别墅，俗称宋庄，后几易其主，其中民国时转售予汾阳人郭士林，因此改称汾阳别墅，俗称郭庄[1]。1989-1991 年整修后对外开放。

    全园平面呈矩形，占地面积 9788 平方米，水面占 29.3%，与西湖相通，建筑面积 1629 平方米，分宅园两部分，分别称静必居和一镜天开，园林部分又分别以南侧的内池（浣池）和北侧的外池（镜池）为中心，两池以中央临池的两宜轩相隔，住宅部分则位于内池东侧和南端[2]。因郭庄东侧紧靠西湖岸边，沿湖建有乘风邀月轩、赏心悦目亭和景苏阁等，其中景苏阁正对苏堤，游人在园内便可饱览西湖风光。

    《庭院照片》

    《园林照片》

  + 上香古道

    上香古道,古代是香客乘船在茅家埠上岸,然后去天竺诸寺上香走的路。现在是杨公堤到茅家埠的一段路。

    由于西湖西进的工程,上香古道从历史中被唤醒并被修复,成为寻幽访古、体验民俗的文化走廊。杨公堤上的卧龙桥和隐秀桥大约相距几十米,其间就是上香古道的入口,上香古道不像苏堤那么直、那么透、那么单调。漫步上香古道,移步换景,一步一景。

    杭州花圃-茅家埠-上香古道-上天竺-法喜寺-中天竺-下天竺，路线景美人少，非常适合拍照。

    《石桥》

    《凉亭》

  + 方桂亭

    《茅家埠水面》

  + 湖光山社
  + 黛色参天
  + 玉涧桥
  + 芳草晴阳
  + 茅家埠
    + 水域大
  + 乌龟潭
    + 长廊

  + [[https://baike.baidu.com/item/%25E4%25BA%258E%25E8%25B0%25A6%25E7%25A5%25A0/11122][于谦祠]]

    于谦祠，位于浙江省杭州西湖三台山麓，西湖乌龟潭畔。于谦是明代的民族英雄，他和岳飞、张煌言并称“西湖三雄”。

    正统十四年（1449 年）“土木堡之变”英宗被俘后，从兵部侍郎升任尚书，拥立景帝，反对南迁。调集重兵，在北京城外击退瓦剌军。

    次年（景泰元年），也先因无隙可乘，被迫释放英宗。

    景泰八年（1457 年）“夺门之变”中英宗复辟，于谦以“谋逆罪”被杀，葬于三台山。

    明朝弘治二年（1489），于谦冤案得以平反,孝宗皇帝表彰其为国效忠的功绩,赐谥“肃愍”，并在墓旁建祠纪念，取名“旌功祠”。

    于谦祠庭院草木葱茏、绿树成荫，是一处清幽之所。

    前殿辟为序厅，殿门两侧楹联是林则徐所撰：“公论久而后定，何处更得此人”。

    清朝嘉庆壬午年（1822）六月，林则徐任浙江杭嘉湖道，他倡议集资整修于谦祠墓，并带头捐献自己的官奉。

    序厅正中一巨大石灰岩上镌刻着前言，石灰岩造型取意于谦青少年时所作诗作《石灰吟》，“粉身碎骨全不怕，要留清白在人间”也正是于谦一生刚正不阿、两袖清风高洁品性的真实写照。

    两侧墙上陈列于谦年表、于谦世系表，一张绘于清代的于谦夫妇像尤为引人注目。厅内还放置造型简洁的案几、椅等明式家具以渲染气氛。

    正殿是于谦祠的主体部分，也是陈列最具特色的地方，通面宽 21.8 米,进深 14.15 米,。大殿正中是一座于谦全身立像，于公威严肃立，双目炯炯，正气凛然。像高 3.2 米，基座 1.3 米，为海水浪花图案。像后衬以由徐向前元帅书写的《石灰吟》壁面，塑像上方悬挂乾隆御题匾额：“丹心抗节”，黑底金字，为乾隆十六年乾隆帝南巡杭州凭吊于谦时所题。

    殿柱上悬挂数幅颂扬于谦不朽功绩的楹联，均是明清时期的名家所撰，经当代书法家题写。

    大殿墙面为两幅半圆大型浮雕壁画，左侧是“北京保卫战”，右侧是“土木堡之变”的有关场景，每幅画相对独立，但在整体上又呵成一气，场面颇为凝重、壮观，运用明暗变幻的灯光效果，再辅以铿锵激越的《十面埋伏》背景音乐，使人产生身临其境之感，恍如置身于刀光剑影、杀声震天、尘土飞扬的古战场，正与于谦一起抵御外侮。壁画高 3 米，宽 46 米，是经专家多次论证修改，在中国美术学院雕塑家王卓予先生的指导下完成。壁画突破了一般祠堂陈列的窠臼，使壁面不见柱子，与匾额、楹联、塑像遥相呼应，具有强烈的艺术震撼效果。

    塑像背面的墙壁上嵌有清代石碑若干块，其中包括湘乡杨昌 题的线刻《明少保兵部尚书赠太傅谥忠肃于公像》碑一块，袁枚题《重修于忠肃庙碑》残碑九块。

    南北厢房分别作为兵器室和接待室。兵器室陈列明代的各种军械，包括神机营用的火铳、火炮等。明代的兵器门类多、数量大、制作精、技术高，有较高的研究和欣赏价值。

    前殿与后殿间的天井里，赫然立着一尊威武、雄壮的铁犀牛，身高约 2 米，围长约 2.5 米，周身乌黑，独角朝天，背上铸有于谦亲撰的《镇河铁犀铭》，它是于谦勤政爱民、治理黄河的一个历史见证。黄河自古多泛滥，巡抚河南期间，他励精图治，奔波于大河上下，全心治理水患。为鼓舞人民战胜洪灾的信心，在 1446 年，派人铸了这尊“镇河铁犀”，表达了希望根除黄河水患，使百姓过上安定幸福生活的美好愿望。原物现存于河南开封铁牛村。

    天井右侧有口井，井旁立碑，名之为“忠泉”。根据祠内清时李铎遗碑记载：康熙乙亥年，在改建于谦祠时发现此泉，泉水色清而味甘，因念“公之大忠诚如水之在地中”，故以此命名。

    后殿的院子里还保存着数明清两代的石碑，分别是四块大碑（弘治、嘉靖、万历、康熙）及一块乾隆年间的残碑。 [2]  里面还有一座摸福兽，传说摸它会有好运。

    + 海棠花开，拍婚纱照

  + [[https://baike.baidu.com/item/%25E4%25B8%2589%25E5%258F%25B0%25E4%25BA%2591%25E6%25B0%25B4][三台云水]]

    三台山景区集浙江山地和江南水乡风貌于一身，它以浴鹄湾景区为核心，东靠杨公堤，西临三台山路，北至乌龟潭景区，南到虎跑路。

  + 先贤堂

    先贤堂亦称集贤堂，始建于宋代，原在苏堤第一桥映波桥旁。宋宝庆二年（1226），京尹袁韶奏请朝廷建一座祠庙，以祭祀杭州自许由以下的三十九位名人贤士。

    祠临湖而建，内设一园，一条迂回曲折的小径贯穿其间，道旁遍植花竹，浓阴蔽日；园内“亭相望五六”，游人由“振衣”亭，经“古香”亭，循“清风”亭，可登至山亭，在“流芳”亭小憩，而后至祠下。

    先贤堂外堂内室，四周环以廊庑，堂门上挂一匾额，上书“仰高”，堂内陈列着刻有诸贤头像和生平事迹的石碑。元初堂废，现地原址附近重建，作为介绍、展示杭州名人文化和纪念缅怀先贤的场所。

  + 湖畔大学

  + 子久草堂

    子久草堂。相传黄公望曾在杭州赤山之阴结庐隐居，茅庐周围风景怡人，倚门眺望还能见雷峰塔之景貌。2003 年于旧居原址附近设黄公望故居陈列室，以纪念这位中国绘画史上杰出画家。

  + 霁虹桥

    霁虹桥位于花港公园以西的浴鹄湾，与黄公望故居、浴鹄轩、黄蔑楼等隔水相望。霁虹桥布局精致、舒展开敞、白墙黑瓦、木石相间、借景湖山、点景自然，体现了湖西景区“野趣、闲趣、逸趣”的景观特点，可游宜憩，融观光与休闲于一体。

  + [[https://baike.baidu.com/item/%25E6%25B5%25B4%25E9%25B9%2584%25E6%25B9%25BE][浴鹄（gu 三声）湾]]

    浴鹄湾景区东靠杨公堤，西临三台山路，北至乌龟潭景区，南到虎跑路。这是西湖大景边的一处小景，悠闲自在的园林小筑，虽然小的可以，但却依山伴水，花花草草的四季常开。

  + 武状元坊

    杭州武状元坊，位于后赤山埠附近。据史书记载，南宋嘉定七年（1214），武状元刘必万（有记载为刘必方）在赤山立武状元坊。现以宋代样式重建武状元坊，以反映杭州古代科举文化。


  + 黄篾楼水轩

    黄篾楼，位于浴鹄湾附近。元代著名文学家张雨构水轩于此，并名曰“黄篾”。刘邦彦有诗云：“春水初生浴鹄湾，篾楼高枕对青山。鸟声啼足忽飞去，门掩绿阴清昼闲。”浴鹄湾附近重建黄篾楼，游人到此歇脚闲坐，静赏四周天然美景，可以唤起对往昔动人意境的美妙想像和感受。

* 西湖路线三
  看点：寺院，自然美景。
  + 灵隐寺

  + 三天竺寺
    + 法净寺，法喜寺，法镜寺

  + 杭州佛学院

  + [[https://baike.baidu.com/item/%25E4%25BA%2591%25E6%25A0%2596%25E7%25AB%25B9%25E5%25BE%2584][云栖竹径]]
    + 卧虎藏龙取景地
    + 人少

* 西湖线路四
  看点：茶园，九溪烟树，浙大之江校区。

  + 太子湾公园

  + 满觉陇

    满觉陇，亦称满陇、满家弄，位于杭州西湖以南，是南高峰南麓的一条山谷。五代后晋天福四年(公元 939 年) 建有圆兴院，北宋治平二年(公元 1065 年)改为满觉院，满觉意为“圆满的觉悟”，地因寺而得名。

    满觉陇因桂花而闻名，每年秋天，桂花盛开，香满空山，落英如雨，故有“满陇桂雨”之美誉。1985 年，“满陇桂雨”被评为新西湖十景之一。

    明代人高濂在《满家弄看桂花》中写道：“桂花最盛处唯南山、龙井为多，而地名满家弄者，其林若墉栉。一村以市花为业，各省取给于此。秋时，策骞入山看花，从数里外便触清馥。入径，珠英琼树，香满空山，快赏幽深，恍入灵鹫金粟世界”。

    清人张云敖有绝句《品桂》云：“西湖八月足清游，何处香通鼻观幽？满觉陇旁金粟遍，天风吹堕万山秋。”

    桂花是杭州的市花，满觉陇自明代起就是杭州桂花最盛的地方。今天，这一带的路旁坡地、崖前涧边，共种植桂花 7000 多株，树龄长的达 200 多年，已成为杭州赏桂花最著名的景点。每到金秋花开时节，这里金桂飘香。

    + 四眼井

      四眼井村靠虎跑路和满觉陇路交叉口两侧，是近年兴起的杭州旅游住宿聚集区，村子不大但集结了二十几家青年旅舍。四眼井在地理位置上有极大优势，它离杭州火车城站只有 6 公里，离著名的西湖苏堤更是只有不到 2 公里，西湖三十景差不多有有一半在距此 3 公里的范围内，交通便利、景点集中、尤其山景优美，颇具野趣。

    + 民宿

  + [[https://baike.baidu.com/item/%25E8%2599%258E%25E8%25B7%2591%25E6%25B3%2589][虎跑泉]]

    虎跑泉位于浙江杭州市西南大慈山白鹤峰下慧禅寺(俗称虎跑寺)侧院内，距市区约 5 公里。虎跑泉的来历，还有一个饶有兴味的神话传说。相传，唐元和十四年（819）高僧寰 中（亦名性空）来此，喜欢这里风景灵秀，便住了下来。后来。因为附近没有水源，他准备迁往别处，一夜忽然梦见神人告诉他说：“南岳有一童子泉，当遣二虎将其搬到这里来。”第二天，他果然看见二虎跑（刨）地作地穴，清澈的泉水随即涌出，故名为虎跑泉。张以宁在题泉联中，亦给虎跑泉蒙上一层宗教与神秘的色彩。

    泉水晶莹甘冽，居西湖诸泉之首，和龙井泉一起并誉为“天下第三泉”。虎跑泉原有三口井，后合为二池。在主池泉边石龛内的石床上，寰中正在头枕右手小臂人侧身卧睡，神态安静慈善，那种静里乾坤不知春的超然境界，颇如一副联语所云：

    梦熟五更天几许钟声敲不破，神游三宝地半空云影去无踪。

    同时，栩栩如生的两只老虎正从石龛右侧向入睡的高僧走来，形象亦十分生动逼真。这组“梦虎图”浮雕寓神仙给寰中托梦，派遣仙童化作二虎搬来南岳清泉之典。“虎移泉眼至南岳童子；历百千万劫留此真源。”----这副虎跑寺楹联也是写的这个神话故事，只是更具有佛教寓意

    苏轼《虎跑泉》诗：
    #+begin_quote
    亭亭石榻东峰上，此老初来百神仰。
    虎移泉眼趋行脚，龙作浪花供抚掌。
    至今游人灌濯罢，卧听空阶环玞响。
    故知此老如此泉，莫作人间去来想。
    #+end_quote


    袁宏道《虎跑泉》诗：
    #+begin_quote
    竹林松涧净无尘，僧老当知寺亦贫。
    饥鸟共分香积米，枯枝常足道人薪。
    碑头字识开山偈，炉里灰寒护法神。
    汲取清泉三四盏，芽茶烹得与尝新。
    #+end_quote


  + 钱塘江大桥

  + 浙江大学之江校区
    + 美景

  + [[https://baike.baidu.com/item/%25E4%25B9%259D%25E6%25BA%25AA%25E7%2583%259F%25E6%25A0%2591][九溪烟树]]

    九溪烟树位于浙江省杭州市的著名景点西湖之西的鸡冠垅下，又称九溪十八涧。这里的溪流、茶园、迷雾、青川，构成了这一景区的四大旅游特色，游人徒步行在高低不平的路径中，但见迷离的雾气似纱如缎地笼罩着山冈上翠绿的茶树，但听潺潺的溪流涧水流淌在垂兰吊藤的山脚岭根，如梦似幻，仿佛走在天庭的长街。

    古时候人们常喜欢用“九”字来表示数量的众多，其实，这座山区的溪流一路上穿林绕麓，不知汇合了多少细流。十八涧，原是指这条山区溪流的源头龙井一带的无数山涧泉流而说的。所以，十八涧也是古时人们用“九”的倍数来形容山涧泉流众多的意思，并非只有十八条山涧。

    诗云：
    #+begin_quote
    春蚕吐丝狮峰织，迷雾流烟扑面湿，
    天光云影青川走，嫩芽翘舌茶花迟，
    千沟万壑十八涧，重峦叠嶂落九溪；
    一路欢歌入钱水，九溪烟树天下知。
    #+end_quote


  + 杨梅岭（不顺路）
    + 民宿

  + 十里琅珰（不去，太远）

    郎当岭，又名琅珰岭，古名扪壁岭。原指天竺山东，龙井村西，梅家坞村东北的山岭。习惯上把南起五云山，北至天竺一带山岗通称“郎当岭”。因山岗蜿蜒约数公里，又有“十里郎当”之称，即“十里琅珰”。郎当岭景区地质地貌以石灰岩为主，自然形成了峰峦叠秀，千姿百态的山林景观，是西湖群山中最高、最长的山岭，平均海拔在 200 米以上，视野开阔，澄静明秀。是深受杭州市民游客喜爱的西湖山林旅游胜地之一。现古道仍保持着原有路径走向和传统的地面铺装

  + 龙井村（不去，太远）
    + 茶园
    + 龙井八景


* 西溪湿地
  + 西溪湿地洪园（龙舌嘴入口）

  + 周家村码头->烟水鱼庄（船）
    + 游览路程：大概 2.5 公里
    + 最佳拍照点：18 处
    + 游览时间：30 分钟

  + 烟水鱼庄->河渚街
    + 游览路程：大概 2 公里
    + 最佳拍照点：15 处
    + 游览时间：30 分钟

  + 河渚街——高庄
    + 游览路程：大概 1.5 公里
    + 最佳拍照点：18 处
    + 游览时间：50 分钟
  + 福堤
  + 绿堤
  + 高庄
