# -*- coding:utf-8-*-
#+TITLE: 贵阳-重庆-成都
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com
#+STARTUP: overview

趁着五一假期来了一次自由行，首先总结一下：
+ 这次旅行很随性，没有提前买票，每个地方感觉玩的差不多了，再买去下一站的票。优点是没有太强的约束性，缺点就是快五一了，每次买票都是看着没票了，然后刷票抢到的。
+ 一个人自由行不好的地方就是不能吃太多，看着那么多好吃的，吃不下去，好难受。
+ 抖音上那么多好看的姑娘说自己单身，但是出来旅游的都是有主的。

* 贵阳（4.28-4.29）
  美食：洋芋耙，青岩状元蹄，豆腐圆子，青岩米豆腐，青岩玫瑰冰粉，花溪牛肉粉。

  景点：甲秀楼，青岩古镇
  早上从乘坐从深圳到贵阳的火车，5个小时的车程。大概中午的时候就到，首先入住小猪短租上面找的房子，位于花果园。楼下公交很方便，不管是去景点，还是去找吃的。

  首先准备去省府路上的老凯俚酸汤鱼火锅，毕竟饿了大半天了。

  路上遇到了粑粑坊，买了一个糍粑，很便宜，才3块钱，味道还不错。

  到了老凯俚以后，点了一份酸汤鱼（江团）和一份丝娃娃。

  酸汤鱼是真的好酸，不过多喝几口，感觉挺好喝的。一个人吃的慢，结果最后鱼都煮化掉了。

  丝娃娃其实和春卷差不多，这家的味道感觉一般，并没有预期的那么好吃，可能要应该去丝恋尝尝。

  然后出门消食，贵阳不大，我都是步行转悠的，小十字，大十字，都在这一块，附近还有个陕西路小吃一条街，后来去青云路找吃的时候才发现陕西路在这边，当时吃不下了，也就没回来找。

  不得不说，着附近真是好多地下通道，走两步就是一个，有的地下通道里面是个商业街，有不少的小店或者小吃。有兴趣的可以转转。

  然后就晃悠着去二十七路小吃街。

  挺长的一条街，也有很多小吃，我尝了豆腐圆子，挺好吃的，粉应该也好吃，但是我真的吃不下了。

  继续消食，去了青云路美食街，完全的大排档模式的，感觉要是人多就在这里吃了，这才是本地人去的地方。

  晃悠着去甲秀楼看看，它对面有个桥，夜景挺好看的，拍两张。

  甲秀楼本身也很美。

  旁边有个。。。应该又是个地下通道，看着色彩也不错。

  就这样第一天就结束了。第二天上午大早起来奔着青岩古镇，直接公交就可以到。

  下车的地方是西门，首先看到的道路两边的商店，来的早，人还比较少。

  今天天气不好，后面还下了点小雨。

  古镇青石铺路，有很多很有意思的小巷子，很适合拍照。

  偶遇两个漂亮的姑娘。

  然后就溜达着去了南门，这时候已经开始下了点小雨了。有个小池塘。。。应该是个池塘吧。。


  然后差不多十一点了，就坐车回住的地方，然后乘高铁去重庆了。

* 重庆（4.29-4.30）
  美食：豆花、酸辣粉、小面、凉虾
  景点：磁器口、三峡广场、解放纪念碑，八一路小吃街

  经过两个小时的车程，4.29 日下午达到重庆，不得不说，这里有个教训：找住的地方应该选在热门景点附近，比如解放碑步行街。结果我左选右选，选在了洋人街附近。离磁器口、解放碑都有点距离，不是很方便，当然住的环境挺好的，

  安排好入住以后，就坐公交去了磁器口，重庆不愧是山城啊，除了桥就没有平路，要么上坡要么下坡。

  到了磁器口以后已经八点多了，逛了一会就九点，很多店都开始关门了，只能随便转转，所以建议去的话还是白天去。

  出来以后，在公交站附近找了个小馆子，点了一份豆花，蘸上店家配的调料，真香，又来了一份。感觉四川的辣椒要比贵州的香。

  还有一份。。我忘记这个是什么了，软软的，有红糖，也挺好吃的。

  离开磁器口，九点半，然后溜达这去三峡广场找吃的，路上遇到一个姑娘在弹吉他唱歌，长得好看，唱歌也好听。感觉可能是刚出来，摆摊在路边一个阴影的地方，夸了句他好听还很害羞。

  去了三峡广场以后，很多店铺也关门了，也没什么小吃。。重庆睡这么早么？看到雷家的小吃店，要了一份酸辣粉，不怎么样，煮太软了，还要了一份凉粉，也不怎么样。

  想着一晚上什么吃的都没有找到，不甘心，然后看了一下地图，不远就是重庆大学的AB校区，他们中间是沙正街，大学附近应该还有吃的吧，结果走了一路，发现我想多了，黑乎乎的什么都没有。路上遇到了九村烤脑花，看了大众点评还不错，进去点烤脑花，茄子，然而挺失望，没有深圳的木屋烧烤好吃。

  吃完了，发现已经十二点了，叫了滴滴准备回家，对了，重庆地铁也十点停运，唉，今天是失败的找食之旅。。

  第二天早上起来，准备换到解放碑附近去住，那里要热闹点，而且离洪崖洞也不远。最后选在了较场口地铁站附近，叫了个滴滴，到了发现是个女司机，还是第一次遇到女司机，然后就打听附近怎么玩，聊天过程中说道了导航，她说在重庆导航没用，当时没在意，然后下午和第二天溜达的才明白，在重庆导航真没什么用，你都不知道下一步是该上天还是入地，出较场口地铁站我上了四层电梯。

  安排入住，在附近晃悠，楼下就是较场口夜市，吃的挺多的


  还是点了一份豆花，味道还是不错。


  好又来酸辣粉，看到有两个本地的大妈再吃，评价也不错，点了一份小面试试，也挺好的

  吃饱了去观音桥小吃街，恩，其实那边是个大商场，有奥特莱斯，但我主要是找吃的去了。

  里面有很多店铺，各种各样的小吃，我只点了章鱼丸子和凉虾，味道都挺好，凉虾不真的有虾。

  然后就回解放路了，广场附近有很多，也有一些有意思的建筑。

  小长假了，洪崖洞桥附近好多人，没有凑热闹去看。

  解放碑下面好多人拍照，我等了两个小时，也拍了一些。

  晚上回去吃了白天女司机推荐的江一娃串串。。感觉味道不咋样，而且居然是称竹签的，竹签那么粗，感觉有点坑。。

* 成都（5.1-5.2）
  美食：
  景点：文殊院，春熙路，太古里，宽窄巷子，锦里

  早上起来睡晚了一点，然后刷到去成都的高铁票，赶紧收拾东西去成都。高铁上还小睡了一会。

  这次学乖了，直接住到了春熙路、九孔桥附近。

  看了地图，计划先逛东边，主要是文殊院、春熙路、九孔桥。明天再去西边，主要是宽窄巷子、锦里、人民公园。而且成都是有共享单车的。

  先去文殊院，跟着美食地图走。

  路上看到好多穿汉服的小姑娘和小汉子，才发现原来有花朝节。

  张老二家的甜水面还不错的，挺有意思的。

  锅盔感觉味道也不错吧，不过味道和我弟做的饼差不多的，没有很惊喜。

  大骨汤抄手，皮薄肉多，味道很好。

  其他的美食一个人没法吃，就没有去找了。

  然后晃悠着了去了明婷饭店，去的时间不早了，人不多，香葱腰花没有了，只点了霸王黄喉和铁板茄子。铁板茄子太油了，味道一般，霸王黄喉味道很好吃，就是黄喉少了点。上面一层是黄喉，下面是金针菇什么的，不过味道的确很不错，而且菜价不贵。

  然后溜达出来，骑车去找同学。

  路上人挺少的，但是经过太古里的时候，我的天，人超多，感觉不知道从哪里钻出来的。不巧的是路上还下雨了。断断续续的一直下到晚上，等在同学家吃完回来，春熙路还是一堆人在雨天里排队。

  本来打算第二天早起去宽窄巷子的，但还是晚了，九点多打车到无名包子铺去买了两个包子，已经不是一块五的价格了，包子个不小，但味道感觉一般吧。

  一边吃一边去宽窄巷子。

  找到个位置很适合拍照的地方，因为刚下过雨，光线很柔软。而且这里墙也高，有阴影，拍照有层次感。


  不知不觉过了挺久，等我出来的时候，外面乌压压的都是人，随着人流四处简单看看。

  出来以后就前往锦里，这时候已经中午了，买了只雪糕，才2块钱，一边吃一遍走。

  锦里也是好多人，挺挤的，顺着人流四处看看。

  最后走到刘湘墓这里的时候，看着这个门洞不错，适合拍照，等了一会，拍了一些照片。

  今天还是有很多穿汉服的。

  看着人少了点，就又忘锦里转，找到一个同心亭的地方，好多锁。

  听到旁边两个哥们商量：“我觉得学个开锁也不错”。

  还遇到一对母女，小孩真可爱。


  休息的时候看了下会深圳的机票挺便宜的，然后就买了机票直接走了。此次行程结束。
