# -*- coding:utf-8-*-
#+TITLE: 2019 青海环线旅游
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 概述
  2019 年公司旅游，总共有国内国外 20 多条旅游线路，其中，日本、迪拜、巴厘岛已经去过，剩下的沙巴、苏梅岛想着也是海岛，景色应该和巴厘岛差不多，看着旅游线路上青海环线位于祖国大西北，而且有高原、雪山、沙漠、草原等多种地貌，还有清真寺、回族、藏族等人文建筑景观可以游玩，便选定了此条线路。

  这次旅行由 “行者无涯” 旅行社承接，出行前一周旅行社相关人员来公司做了答疑。

* 出行准备

** 衣
   根据天气预报，6 月份当地温度 9℃ ~ 23℃ ，所以需要准备 *防风外套* 。

   由于当地太阳直射，紫外线较强，需要携带 *防晒衣帽，墨镜，高倍数防晒霜*

   由于当地早晚温差较大，需要准备厚外套或者冲锋衣。

   考虑到当地可能有风雨，需要准备鞋套、长款雨衣，拖鞋，鞋套和拖鞋去茶卡盐湖也可以用到。

   综上所述，需要准备以下东西：
   + （done）渔夫帽，防晒。
   + （done）墨镜，选择镜面比较高亮反光的夹片式墨镜。
   + （done）防晒霜，选择膏状涂抹，而不是喷雾，避免机场不让携带。
   + （done）鞋套，拖鞋。
   + （done）长款雨衣。
   + （done）徒步鞋，SCARPA 高靴徒步鞋，有徒步行程，有利于防水，保护脚踝。
   + （done）擦汗毛巾。
   + （done）短袖 * 2。
   + （done）短裤 * 2。
   + （done）长裤 * 2。
   + （done）换洗内衣 * 4。
   + （done）带有抓绒内衬的冲锋衣，颜色鲜艳，选择黄色。
   + （done）干衣神器，简易衣架，用来烘干换洗衣物。
   + （done）驱蚊水，夏天北方也是有蚊子的，不能携带蚊帐，驱蚊水比较合适。最后表明，当地气温还是比较低，没有遇到蚊子。

** 食
   北方气候干燥，需要经常补充水分，自带水杯 。

   感觉自身情况不错，沿途海拔也不算高，所以不准备高反药物。

   综上所述，需要准备以下东西：
   + （done）水杯。

** 住
   旅店安排住宿，自己携带个人卫生用品：
   + （done）牙膏、牙刷、洗面奶、剃须刀，小瓶装，方便携带。
   + （done）洗发水、沐浴露。

** 行
   + （done）充电宝，充电线。
   + （done）万能插头。
   + （done）纸巾、湿巾。
   + （done）零钱
   + （done）kindle，路途上看书，打发时间。

** 摄影

*** 相机
    自有 sony a7M3 ，可以用来拍摄风景。

    还有iphone x，可以抓拍一些简单场景，或者全景照片。

*** 镜头
    选择 sony FE 16-35mm F2.8 镜头作为主力镜头，原因如下：
    + 主要是拍摄风景，包括大清真寺、草原、雪山、茶卡盐湖等，需要广角镜头。
    + 有部分的人文拍摄场景，包括当地人文，团友拍照，需要大光圈，35mm 可以凑合和用，所以没有选择 sony 12-24mm F4 镜头。
    + 需要拍摄夜景，行程安排有拍摄星空，需要广角+大光圈。

    该镜头是通过淘宝租赁的，店铺名字是“兰拓相机租赁”。兰拓是一家信誉非常好（双冠）的镜头商家，之前看过他家做的一些镜头相关的评测。而且他家租赁镜头还有很多优惠，比如我在这篇 2000 字以上的游记里面提到，并且写相关体验，就会有 100 的返现，当然服务好才是最重要的。

    此外还自有 sony FE 24-70mm F4 镜头，可以作为补充。

    后记：在游玩过程中，一直豆仔使用 16-35mm 作为主力镜头拍摄美人和美景，16mm 广角来拍摄茶卡盐湖很美，用来拍摄随团的姑娘们也很显身材。 35mm 拍摄一些人文，也比较合适。 2.8 的大光圈虚化，拍夜景都很合适。

    整个相机租赁过程，都很干净利落，店家收到回寄的相机不到 12 小时就返还了押金，下一步还准备组个 50mm F1.8 的定焦镜头玩玩。

*** 配件
    + 三脚架：拍摄风景自然不能少三脚架，暂时用的是买相机时送的三脚架。还有一个八爪鱼三脚架。
    + 快门线：星空，自拍少不了快门线。为此买了斯丹德的无线快门线。
    + 背包：摄影背包使用之前买的乐摄宝 PROTACTIC BP 450AW 二代，这个背包很大，可以把相机，两个镜头，快门线都装进去。
    + SD 卡：两张 64GB 的 sd 卡，拍摄过程中同时保存 raw+jpg 格式图片.

    后记：旅游过程中，没有机会拍星空，三脚架和快门线没有用上，不过专业背包用来存取相机都很方便。SD 卡差点不够用，多准备一张心里还是有底。

* D1 深圳->西宁
  6.20 早上乘坐深圳航空从深圳飞往西宁（08:40-12:15），然后先入住西宁凯旋国际酒店。

  办理入住之后，几个人出去在附近找家小餐馆吃了份羊杂面，嗯，面里加的辣椒有点辣，配汤里面也加了胡椒粉，感觉汤还是挺好喝的。羊肠应该是素羊肠，感觉有淀粉。

  《羊杂碎面》

  然后回酒店，休息到三点半集合，去东关清真大寺。在东关清真大寺游览大约1个小时，大部分时间是在听解说，这个清真寺整体不大，那些红色油漆的柱子，楼梯，白色的栏杆等地方还是拍照蛮合适的，但是行程紧凑，并没有留很多拍照的时间，等最后一天回来的时候再拍照吧。

  下午大约 5 点，走路去莫家街逛，其实没什么好逛的，特别短的一条商业街，不建议去。

  下午大约 6 点去益鑫吃手抓羊肉，西北菜都很大份，千万不要点多，推荐：
  + 黄焖手抓羊肉，蘸上椒盐和辣椒酱，配置紫皮大蒜吃，没有一点羊膻味。
  + 酸奶，有点酸酸的，和平常的酸奶味道不一样。
  + 炸土豆块。
  + 西湖牛肉羹。

  吃完各自回家，我自己走路回清真大寺，打算拍夜景。回到清真寺以后，在阁楼上，和两个工作人员聊了一下伊斯兰教的文化，朝拜习惯等。

  晚上8:40 左右当地开始做第四次礼拜，看了好多人都开始陆陆续续走进大店开始做礼拜。我过去观察了一会，看到都是男性。

  等他们做完礼拜往出走的时候，就和一个信徒聊，他跟我说男女不在一起做礼拜，女性都在家里做礼拜，然后我们开始聊伊斯兰教文化和汉族文化的异同，已经伊斯兰教认为人性本善等。

  晚上9:40 左右开始做第五次礼拜，我开始拍了两张夜景。

  尝试拍摄大门全景未果，看周围条件，应该需要在对面找个好的机位。

** 东关清真大寺

   拍摄重点：
   + 清真寺建筑的宽大和宏伟。
   + 建筑细节。
   + 低角度拍摄人物和建筑，形成大小对比。
   + 名族和宗教特色的人物服饰、举止。

   清真大寺是西宁古城著名的建筑，位于西宁东关大街路南一侧。据说创建于明朝（1368——1644）初期，历史上曾经多次遭到破坏，又不断修建，现存的建筑是1913年时重建，1946年时改建并扩建，1979年时又重修。其与西北地区著名的西安化觉寺、兰州桥门寺、新疆喀什艾提卡尔清真寺并称为西北四大清真寺。

   该寺建造雄奇，坐西面东，其风格融合了中国传统的建筑艺术和伊斯兰教建筑特色，雕梁彩檐、金碧辉煌，大殿内宽敞、高大、明亮。

   正门高10米，宽15米，上面写着该寺的名字；正门内耸立着5个拱门，高10米，宽21米；

   《正门照片》

   再里面是面积达4490平方米的大院；

   《广场照片》，低角度拍摄。

   正中间是礼拜大殿，面积1136平方米，砖木结构，其建筑形式是卷棚、大殿、后窑殿合为一体。

   《礼拜大殿照片》

   《其他建筑照片》

   《人文照片》

   夜景也很漂亮。

   《夜景照片》


** 西宁美食
   后记：我居然支持了下面的一种。
*** 城东区
    + 炮仗面：火车站附近的元青牛肉拉面
    + 褪骨牦牛肉：八一路大众街 25 号白驼牦牛肉
    + 回族点心：各种花花，南关街
    + 凉皮：南关街华联超市门口的凉皮，下午四点以后就卖完了。
    + 烤羊肉：兴海路马一刀烤羊肉
    + 牛肉面：兴海路木桥牛肉面
    + 甜醅，酸奶：兴海路
    + 手抓羊脖子：堪称西宁一绝。成贵羊脖子。
    + 羊杂汤：是西宁街头很普遍的早餐之一。晓泉羊杂碎，早上六点开始卖，中午就卖完了。
    + 青海土火锅：西宁市城东区乐都路国际村旁
    + 手抓羊肉：益鑫，城东区七一路21号。（done）

*** 城西区
    + 涮羊肉：瘦珠玑巷，京味涮羊肉
    + 兰州玫瑰饼：瘦珠玑巷，
    + 羊肠面：尕（ga 三声）晋娃羊肠面。

*** 城中区
    + 炕羊排：是西宁人聚会必点的硬菜，盆里有金黄的土豆片、宽粉、红绿辣椒、洋葱，香菜，交通北口炕羊排
    + 干煸羊肠
    + 胡辣羊蹄
    + 酿皮：南山路的小吴酿皮（地址：城中区南山路美多发艺隔壁，人均 7 元），
    + 青海土火锅：城中区饮马街口，近十四中。
    + 洋芋抓面，炕羊肠，酸汤：马贵，城中区互助巷14号
    + 仙红辣椒酱
    + 羊杂碎：泉儿头杂碎（出名）

* D2 西宁->门源->祁连八宝镇
  7:00 起来在酒店吃早饭，整体感觉还是比较丰盛的。

  8:30 下楼集合，经过大约4个小时车程，到达了青石嘴镇。

  途径：
  + 黑泉水库，路过，但是没有停车，没有看到更好的风景。
  + 仙米林场，路过，没注意。
  + 达坂山，穿过了中国最高的公路隧道-达坂山隧道。

  一路上天空的云彩很好看，我脑洞大开，拍了好多。

  《云彩照片》

  两边还能看到刚出嫩芽的心草，然而，更多的是对西北脆弱生态环境的担心：草只有薄薄的一层，下面就是砂石。

  《山丘和草皮》

  到青石嘴镇以后吃午饭，品尝了当地的盖碗茶，里面有几种干果，比如龙眼、猕猴桃等，加了不少冰糖，所以很甜，当地人喜欢吃甜食。还有火锅（什么火锅来着？）。当然又吃了当地的酸奶。

  吃饭中间下过短暂的一场大雨，碧空如洗，特别漂亮。

  《雨后照片》

  还能看到远处冰雪覆盖啊的祁连山。

  《雪山照片》

  乘车游览卓尔山，登山前导游让我们带好雨伞雨衣，因为山上可能会下雨，果不其然，登山以后就开始下小雨，断断续续的。

  我们顺着木质栈道到达山顶，在烽火台避雨。

  然后去了“民族团结塔”，可能是叫这个名字，对面还是雪山，可能还是祁连雪山？远处的山峰光线特别好看

  《团结塔》

  《阴影山峰》

  不过更加惊喜的是雨停后出太阳了，正好在山顶看到一个彩虹桥，赶紧拍拍拍。

  《彩虹》

  大约六点的时候开始下山，远处看着绿色和紫色的农田，虽然不知道种的是什么，但是好看。

  《农田色块》

  这时候山上已经是乌云压顶，看着山上应该是更大的雨，今天运气真好。

  晚上吃的小火锅，牛羊肉管饱，还喝了点青稞酒。

** 黑泉水库
   黑泉水库，位于227国道旁，距离西宁市75公里，对保障西宁及周边地区的工农业及生活生态用水具有重要的作用。

** 门源仙米森林公园
   没有停留游览。

** 门源达坂山
   拍摄重点：
   + 路上拍摄的天空云彩
   + 远处的雪山

   达坂山地处青海省大通与门源两县的交界处，是青海通往甘肃的交通要道。这里是门源油菜花三个最佳观赏地点之一。

   油菜花没有开，没有停车，路上遇到一次很急的雨。

** 门源青石嘴镇
   青石嘴镇有丰富的旅游资源和矿产资源，属国家AAAA级旅游景区，著名的圆山观花台就位于此。（后记：没去）

   《祁连雪山》

** 祁连卓尔山
   拍摄重点：
   + 木栈道
   + 山两侧风景，地貌

   卓尔山景区项目建设地位于青海省祁连县八宝镇，紧靠八宝河与藏区神山阿咪东索（牛心山）隔河相望。
   卓尔山藏语称为"宗穆玛釉玛"，意为美丽的红润皇后。传说祁连县之所以山清水秀、牛羊肥壮、物产丰富，其原因是就在于她这位来自龙界的王后：因为藏族的传统观念中龙神是财富的主人和象征，守护着秘密的财富。传说宗姆玛釉玛原为一龙界公主，一次偶然的邂逅，使她深深爱上了守护这里的山神——英武非凡的的阿咪东素，甘愿冒犯天规，冲突冲冲阻碍，嫁给阿咪东素为妃，龙王夫妇虽然坚决反对他们成亲，但她还是选择留在人间，与阿咪东素隔河相望，不离不弃。当然她为此付出了代价，变成一座石山。即使这样，她也无怨无悔，因为她和恋人——阿咪东素终身相伴守护着祁连的秀美山川和物华。

   卓尔山属于丹霞地貌，由红色砂岩、砾岩组成。站在卓尔山顶视野极度开阔，四周没有任何遮拦，山对面是一山尽览四季景色的牛心山，左右两侧分别是拉洞峡和白杨沟风景区，背面是连绵起伏的祁连山，山脚下滔滔八宝河像一条白色的哈达环绕在县城周边。处处美景，宛如仙境，令人心旷神怡。

   《木质栈道》

   《丹霞地貌》

   在登山路上看到了特殊的地貌，一块块紫色绿色交错的农田。

   《农田》

** 八宝镇
   吃牛羊肉土火锅，入住天境卓尔国际饭店。

* D3 祁连八宝镇->青海湖

** 冰沟林海
   冰沟林海由于环保原因，不让进去了，只能沿着不远的小溪进行徒步。
   + 自然风光
   + 树木的高大
   + 森林环境的幽暗
   + 河流慢门

   《小溪河流》

   《叠石头》


** 大冬树山垭口
   大冬树山垭口是西宁去祁连路上会经过的地方，海拔4120米，是很多游客此行经过的最高海拔点。山口风不小，拍照要注意保暖。

   《垭口照片》

   回程途中遇到一个藏经筒，有人在那边祈福。

   《藏经筒》

** 青海湖大酒店。

   入住的时候正好有落日，阳光照在走廊上，光线非常好。

   《走廊照片》

   晚霞也很好看。

   《晚霞照片》

   晚上有篝火晚会，大家一起跳锅庄舞。

   《篝火照片》

   《跳舞照片》

* D4 青海湖->茶卡盐湖->西海镇

  今天主要游览茶卡盐湖，白天乘车 2.5 个小时前往柴达木盆地，终于看到了著名的茶卡盐湖。游览完经过 4 个小时到达西海镇，入住海北酒店。

** 青海湖边
   原本计划早上起来看日出的，结果云太厚，只能拍点海边的景色了。

** 茶卡盐湖
   拍摄重点：
   + 盐湖的宽广，水面的反射
   + 盐湖中人物的站姿
   + 盐湖中人物蹲下摸水面

   茶卡盐湖也叫茶卡或达布逊淖尔，"茶卡"是藏语，意即盐池，也就是青盐的海;"达布逊淖尔"是蒙古语，也是盐湖之意。茶卡盐湖是柴达木盆地四大盐湖中最小的一个，也是开发最早的一个，茶卡盐湖与其它盐湖不同的是，茶卡盐湖是固液并存的卤水湖，镶嵌在雪山草地间而非戈壁沙漠上。

   可以乘坐小火车，到盐湖的深处观光，小火车 50/人。

   《火车》

   到达重点以后，下车拍照，今天日光不是很烈，光线刚刚好。

   《湖边人像》

   茶卡盐湖面积空旷、地势平坦，湖面极具有强烈的反射能力，如同一面为天空梳洗打扮而准备的镜子，被称为中国的“天空之镜”。 “天空之镜”最佳拍摄时间为早晨9点之前和下午5点之后。

   《湖面》

   游客可以赤脚走到湖面上观看和拍摄自己的倒影，如果足够幸运，白天可以看到在这些河面上形成的海市蜃楼。

   《湖中倒影》


* D5 青海湖->西宁
  今天主要是文迦牧场游玩，然后下午返回西宁。

** 文迦牧场
   今天我们前往文迦牧场游玩，“文迦牧场”介绍。

   首先是牧场的接待仪式：

   《献哈达》

   《藏包体验》

   《酥油茶》

   《青稞酒》

   《敬酒歌》

   整个过程大约半个小时，然后骑乘草原越野摩托，八公里，来回大约 2 小时。

   《草原越野摩托》

   午餐是藏式土火锅。

   下午是骑马体验，有专业的马夫牵马，不能自己骑。

   《骑马》

   《青海湖全貌》

** 青海湖
   青海湖，藏语名为“措温布”（意为“青色的海”）。位于青藏高原东北部、青海省境内，中国最大的内陆湖、咸水湖。由祁连山脉的大通山、日月山与青海南山之间的断层陷落形成。

** 入住西宁凯旋国际酒店。

* D6 西宁->深圳
  自由活动，特产：老酸奶，牦牛肉干，手抓羊肉

  6.25 乘坐深圳航空从西宁飞回深圳（14:40-17:45）。
