# -*- coding:utf-8-*-
#+TITLE:  Kinesis Advantage
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com

* 概述
  Kinesis Advantage 是一款人体工程学键盘。支持 windows，pc，mac 系统。主要有以下分类：

  + Advantage (PC & Mac)

    是 Kinesis Advantage 的入门款。是茶轴键盘。

  + Advantage LF(PC&Mac)

    LF（Low-force）的键盘是红轴机械键盘。

  + Advantage QD(PC&Mac)
    这一款是 Dvorak 键盘布局的键盘。

  还有一些高级款键盘，比如银色的 Advantage2 Silver，Advantage2 Signature Series。

  + Advantage Silver

  + Advantage2 Signature Series (PC & Mac)

* 使用

** 配置使用模式
   Advantage USB MPC 键盘有三个预配置布局，每个都针对不同的操作系统进行了优化：Windows，PC（非 Windows）和 Macintosh。 键盘是初始默认 US-module 为 Windows 模式，非 US-module 为 PC 模式。

   提供了两个额外的键帽和键帽移除工具可以用来切换 mac 和 windows 按键。

   要更改即时配置设置，最好打开一个文本编辑器。 使用数字行中的 = 键作为修饰符，按住它的同时，点击 P for PC 模式（无 Windows 键），或 W for Windows 模式，或 M for Mac 模式，然后释放 = 键。

   具体图片参见手册。

** 数字键盘

   Advantage 键盘具有第二层键操作，称为 “嵌入层”。嵌入层包括键盘右侧的完整数字键盘。Kinesis 键盘使用 Space 键为 0 并包含 = 键。

   要打开嵌入层，请点击右上角 keypad 功能键，然后再次点击以将其关闭。

   必须打开 Num Lock 才能使用嵌入式键盘创建数字。关闭 Num Lock 后，这些键会执行光标移动操作。

** 更改 Num Lock 状态

   要更改 “Num Lock” 的状态，请按键盘功能键，然后按 Nm Lk 键（在顶部数字行的 “7＆” 键的正面上）。

** LED 指示灯

   Kinesis 键盘中心附近有四个绿灯（LED）。最左边的 LED（“A”）是大写锁定，然后是 Num Lock（“1”），Scroll Lock（↓）和 keypad。大多数电脑都默认开启 Num Lock。不要担心这一点，因为 LED 持续很长时间并消耗很少的功率。

** 打开和关闭切换键的音调（Progrm + 连字符 / 短划线键）

   键盘包括可以打开和关闭的按键的可听音调。这些包括 Caps Lock，Num Lock，Keypad，Scroll Lock 和 Insert。当键盘与 PC 一起使用时，在打开上述键时会发出两次音，而在键关闭时发出一次声音。要关闭这些音调，请按住 Progrm 并按下连字符或下划线键（位于右侧键槽的右上角）。如果您想再次打开音调，请重复此过程。

**  打开和关闭按键点击功能（Progrm + \ | 键）
   默认情况下，键盘包含所有键的可听单击。要关闭按键，请按住 Progrm，然后按下位于连字符和下划线正下方的反斜杠键（“\”）。如果您希望再次打开按键，请重复此过程。

** 重新映射
   重新映射是一项允许您移动，交换，复制甚至取消激活单个键操作的功能。 （请注意，键帽不是为了移动而设计的）。您的 Advantage 键盘具有无需驱动程序即可完成此操作的独特功能。

** 重映射过程（Progrm + F12）
   要重新映射键操作，请按住 Progrm 键并点击 F12（也标记为 Remap），然后放开两个键。键盘的指示灯将开始快速闪烁。点击要在其他位置复制其操作的键（源键）。LED 将开始缓慢闪烁。现在点击要在其中显示新操作的键（目标键）。LED 将再次快速闪烁。要重新映射多个密钥，请重复此过程。您无需退出键之间的重映射模式。

   完成更改后，按住 Progrm 键并点击 F12 退出重映射。灯应立即停止闪烁。您必须退出重新映射键盘以执行您所做的更改。

** 重新映射时，默认布局始终可用
   处于重新映射模式时，出厂配置的键布局始终处于活动状态。没有 key 可以通过重新映射 “丢失”。

** 从嵌入层 remap 或 remap 到嵌入层
   要将嵌入的键操作重新映射到方便的上层位置，请在进入重新映射模式之前打开嵌入层。点击 “源” 键后，点击 keypad 切换回顶层，然后点击您想要新操作的 “目标” 键。

   要从顶层重新映射到嵌入层，请按照正常的重新映射过程，但在点击 “目标” 键之前点击 keypad。

** 在 QWERTY 和 Dvorak 之间切换
   要激活 “板载” Dvorak 布局，请按住 Progrm + Shift + F5。重复此序列以返回默认的 QWERTY 布局。请注意，激活 Dvorak 布局将删除您可能已执行的任何其他重新映射，但宏不会被删除。如果您想自定义键盘并在 QWERTY 和 Dvorak 之间来回切换，请使用宏进行特殊更改。此外，即使录制在 QWERTY 中，宏也能正常播放，当键盘切换到 Dvorak 时播放。

** 宏
   宏可以让您自动化常用的短语或组合键。宏是快捷方式和节省时间，可减少笨拙，复杂或重复性任务所需的击键次数。基本上你通常用键盘输入的任何东西都可以存储为宏。您的 Advantage 键盘具有无需驱动程序即可完成此操作的独特功能。通常允许最多 24 个宏，每个最多约 55 个字符（使用 Advantage Pro 型号时最多约 120 个字符）。

** 宏修改键和宏触发键
   编程宏时，必须首先指定将播放宏的一个或多个键（“触发器”）。触发器可以是任何字母，数字或导航键（但不能是 Shift，Ctrl 或 Alt 等修饰符）。这样的键也可以与一个或多个修改键组合。例如，可以通过 Capslock 触发宏，并且可以通过 Shift-Capslock 或 Ctrl-Shift-Capslock 触发不同的宏。键盘不允许您单独使用修饰符来触发宏，除非它首先被重新映射为非修饰键（参见上文）。可以使用右侧或左侧修改器激活在触发器中包含修改键的宏。

** 创建宏（Progrm + F11）
   要创建宏，请按住 Progrm 键并轻触 F11，然后释放两个键。键盘的指示灯将开始快速闪烁。点击将播放宏的键或键组合（灯光将开始缓慢闪烁）。现在输入您希望包含在宏中的一个或多个键。完成后，按住 Progrm 键并点击 F11 退出。灯应立即停止闪烁。如果没有，您可能已将 F11 添加到宏的末尾，并需要重复此过程。

** 重置键盘内存和内存锁定
   如果键盘行为异常或者您希望重新创建出厂设置，首先要尝试的是内存重置。注意重置键盘内存不会影响 “即时配置” 设置。下面描述两种不同的存储器复位过程。

*** 内存锁定
    如果您有 Advantage Pro 型号，请确保内存锁定开关位于右侧（未锁定）。可以使用名片的边缘或小的折叠的常规厚度纸张移动开关。


*** 存储器复位，选项一（Progrm + Shift + F10）
    此过程将擦除所有重映射和宏。它不会将 Dvorak 切换回 QWERTY，反之亦然。按住 Progrm 键，然后按下其中一个 Shift 键，最后是 F10 功能键，按下所有三个键。键盘上的指示灯应该开始闪烁。释放 key。闪烁停止时，键盘的内存已重置。 （这可能需要几秒钟才能完成）。

*** 存储器复位，选项二（F7）
    此过程比选项一更激进，并将内存完全重置为出厂设置（24 个宏，QWERTY 布局）。在打开计算机电源之前按住 F7 键。启动计算机，几秒钟后，释放 F7。如果在释放 F7 后键盘的指示灯闪烁几次，则表示成功复位。
