# -*- coding:utf-8-*-
#+TITLE: openresty
#+AUTHOR: liushangliang
#+EMAIL: phenix3443+github@gmail.com


* 镜像
  [[https://hub.docker.com/r/openresty/openresty][openresty]] 构建了两种镜像：
  + 从上游构建，这种构建基于特定系统的包管理系统以及对应的 openresty 源。
  + 从源码构建，包括依赖的第三方库。旨在用于更高级和自定义的用法。


  从 1.13.6.1 开始，发行版使用 =<openresty-version>-<image-version>-<flavor>= 进行标记。最新的镜像版本也被标记为 =<openresty-version>-<flavor>= 。 master 分支的 HEAD 也标明为 =<flavor>= 。内部版本由 Travis-CI 和 Appveyor 管理（适用于 Windows 镜像）。

  从 1.15.8.1 开始，对于不支持 SSE 4.2 的系统（例如，较旧的系统和嵌入式系统），还有 =-nosse42= 镜像。它们是使用 =-mno-sse4.2= 附加到构建参数 =RESTY_LUAJIT_OPTIONS= 来构建的。如果系统支持 SSE 4.2，则强烈建议不要使用这些选项，因为 CRC32 指令会大大提高大字符串的性能。这些仅适用于从源构建的镜像，例如 =1.15.8.1-3-bionic-nosse42、1.15.8.1-3-alpine-nosse42、1.15.8.1-3-alpine-fat-nosse42= 。

  强烈建议使用基于上游的镜像以获得最佳支持。为了获得最佳稳定性，请将镜像固定在完整标签上，例如 =1.15.8.1-3-bionic= 。

* 使用

  docker-openresty 将 =/usr/local/openresty/nginx/logs/access.log= 和 =error.log= 分别软链接到了 =/dev/stdout=  和 =/dev/stderr= ，以便 docker logging 可以正常工作。如果更改 =nginx.conf= 中的日志路径，则也应该对这些路径进行符号链接。

  临时目录（例如 =client_body_temp_path= ）存储在 =/var/run/openresty/= 中。可以考虑挂载该卷，而不是写入容器本地目录。 Windows 尚未完成此操作。

* 配置文件
  Docker 工具会安装自己的 nginx.conf 文件。如果要直接覆盖它，则可以在自己的 Dockerfile 或通过卷绑定安装替换它。

  对于 Linux 镜像， =nginx.conf= 中有指令 =include /etc/nginx/conf.d/*.conf;= ，因此将包含该目录中的所有 nginx 配置。默认虚拟主机配置具有原始的 OpenResty 配置，并已复制到 =/etc/nginx/conf.d/default.conf= 。

  可以直接覆盖 =default.conf= 或将 =/etc/nginx/conf.d= 目录绑定到自己的配置目录：

  #+BEGIN_SRC sh
docker run -v /my/custom/conf.d:/etc/nginx/conf.d openresty/openresty:alpine
  #+END_SRC

  如果您在 selinux 主机（例如 CentOS）上运行，则可能需要在卷绑定参数添加 =:Z=
  #+BEGIN_SRC sh
docker run -v /my/custom/conf.d:/etc/nginx/conf.d:Z openresty/openresty:alpine
  #+END_SRC

  使用 Windows 镜像时，您可以直接更改主要配置：
  #+BEGIN_SRC sh
docker run -v C:/my/custom/nginx.conf:C:/openresty/conf/nginx.conf openresty/openresty:windows
  #+END_SRC

* LuaRocks
  在 alpine-fat，centos 和 xenial 变体中包含 LuaRocks。aipine 中没有是因为它通常需要构建系统，我们希望保持该变体的精简。

  它位于 =/usr/local/openresty/luajit/bin/luarocks= 。可以在依赖的 Dockerfiles 中添加包，如下所示：
  #+BEGIN_SRC dockerfile
RUN /usr/local/openresty/luajit/bin/luarocks install <rock>
  #+END_SRC
